/*
XI Sdk Resellers

For resellers seeking to innovate with Ingram Micro's API solutions, automate your eCommerce experience with our array of API's and webhooks to craft a seamless journey for your customers.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package xi_sdk_resellers

import (
	"encoding/json"
)

// checks if the QuoteDetailsResponseProductsInnerPrice type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &QuoteDetailsResponseProductsInnerPrice{}

// QuoteDetailsResponseProductsInnerPrice struct for QuoteDetailsResponseProductsInnerPrice
type QuoteDetailsResponseProductsInnerPrice struct {
	// Ingram Micro quoted price specific to the reseller and quote.
	QuotePrice *float32 `json:"quotePrice,omitempty"`
	// Manufacturer Suggested Retail Price
	Msrp *float32 `json:"msrp,omitempty"`
	// Extended MSRP - Manufacturer Suggested Retail Price X Quantity
	ExtendedMsrp *float32 `json:"extendedMsrp,omitempty"`
	// Extended reseller quoted price (cost to reseller) X Quantity
	ExtendedQuotePrice *float32 `json:"extendedQuotePrice,omitempty"`
	// Discount off list percentage extended
	DiscountOffList *string `json:"discountOffList,omitempty"`
	Type *string `json:"type,omitempty"`
	RecurringPriceModel *string `json:"recurringPriceModel,omitempty"`
	UnitOfMeasure *string `json:"unitOfMeasure,omitempty"`
	Tax *string `json:"tax,omitempty"`
	Extrafees *float32 `json:"extrafees,omitempty"`
	ExtraFeesDetails []QuoteDetailsResponseProductsInnerPriceExtraFeesDetailsInner `json:"extraFeesDetails,omitempty"`
	Discounts []QuoteDetailsResponseProductsInnerPriceDiscountsInner `json:"discounts,omitempty"`
}

// NewQuoteDetailsResponseProductsInnerPrice instantiates a new QuoteDetailsResponseProductsInnerPrice object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewQuoteDetailsResponseProductsInnerPrice() *QuoteDetailsResponseProductsInnerPrice {
	this := QuoteDetailsResponseProductsInnerPrice{}
	return &this
}

// NewQuoteDetailsResponseProductsInnerPriceWithDefaults instantiates a new QuoteDetailsResponseProductsInnerPrice object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewQuoteDetailsResponseProductsInnerPriceWithDefaults() *QuoteDetailsResponseProductsInnerPrice {
	this := QuoteDetailsResponseProductsInnerPrice{}
	return &this
}

// GetQuotePrice returns the QuotePrice field value if set, zero value otherwise.
func (o *QuoteDetailsResponseProductsInnerPrice) GetQuotePrice() float32 {
	if o == nil || IsNil(o.QuotePrice) {
		var ret float32
		return ret
	}
	return *o.QuotePrice
}

// GetQuotePriceOk returns a tuple with the QuotePrice field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuoteDetailsResponseProductsInnerPrice) GetQuotePriceOk() (*float32, bool) {
	if o == nil || IsNil(o.QuotePrice) {
		return nil, false
	}
	return o.QuotePrice, true
}

// HasQuotePrice returns a boolean if a field has been set.
func (o *QuoteDetailsResponseProductsInnerPrice) HasQuotePrice() bool {
	if o != nil && !IsNil(o.QuotePrice) {
		return true
	}

	return false
}

// SetQuotePrice gets a reference to the given float32 and assigns it to the QuotePrice field.
func (o *QuoteDetailsResponseProductsInnerPrice) SetQuotePrice(v float32) {
	o.QuotePrice = &v
}

// GetMsrp returns the Msrp field value if set, zero value otherwise.
func (o *QuoteDetailsResponseProductsInnerPrice) GetMsrp() float32 {
	if o == nil || IsNil(o.Msrp) {
		var ret float32
		return ret
	}
	return *o.Msrp
}

// GetMsrpOk returns a tuple with the Msrp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuoteDetailsResponseProductsInnerPrice) GetMsrpOk() (*float32, bool) {
	if o == nil || IsNil(o.Msrp) {
		return nil, false
	}
	return o.Msrp, true
}

// HasMsrp returns a boolean if a field has been set.
func (o *QuoteDetailsResponseProductsInnerPrice) HasMsrp() bool {
	if o != nil && !IsNil(o.Msrp) {
		return true
	}

	return false
}

// SetMsrp gets a reference to the given float32 and assigns it to the Msrp field.
func (o *QuoteDetailsResponseProductsInnerPrice) SetMsrp(v float32) {
	o.Msrp = &v
}

// GetExtendedMsrp returns the ExtendedMsrp field value if set, zero value otherwise.
func (o *QuoteDetailsResponseProductsInnerPrice) GetExtendedMsrp() float32 {
	if o == nil || IsNil(o.ExtendedMsrp) {
		var ret float32
		return ret
	}
	return *o.ExtendedMsrp
}

// GetExtendedMsrpOk returns a tuple with the ExtendedMsrp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuoteDetailsResponseProductsInnerPrice) GetExtendedMsrpOk() (*float32, bool) {
	if o == nil || IsNil(o.ExtendedMsrp) {
		return nil, false
	}
	return o.ExtendedMsrp, true
}

// HasExtendedMsrp returns a boolean if a field has been set.
func (o *QuoteDetailsResponseProductsInnerPrice) HasExtendedMsrp() bool {
	if o != nil && !IsNil(o.ExtendedMsrp) {
		return true
	}

	return false
}

// SetExtendedMsrp gets a reference to the given float32 and assigns it to the ExtendedMsrp field.
func (o *QuoteDetailsResponseProductsInnerPrice) SetExtendedMsrp(v float32) {
	o.ExtendedMsrp = &v
}

// GetExtendedQuotePrice returns the ExtendedQuotePrice field value if set, zero value otherwise.
func (o *QuoteDetailsResponseProductsInnerPrice) GetExtendedQuotePrice() float32 {
	if o == nil || IsNil(o.ExtendedQuotePrice) {
		var ret float32
		return ret
	}
	return *o.ExtendedQuotePrice
}

// GetExtendedQuotePriceOk returns a tuple with the ExtendedQuotePrice field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuoteDetailsResponseProductsInnerPrice) GetExtendedQuotePriceOk() (*float32, bool) {
	if o == nil || IsNil(o.ExtendedQuotePrice) {
		return nil, false
	}
	return o.ExtendedQuotePrice, true
}

// HasExtendedQuotePrice returns a boolean if a field has been set.
func (o *QuoteDetailsResponseProductsInnerPrice) HasExtendedQuotePrice() bool {
	if o != nil && !IsNil(o.ExtendedQuotePrice) {
		return true
	}

	return false
}

// SetExtendedQuotePrice gets a reference to the given float32 and assigns it to the ExtendedQuotePrice field.
func (o *QuoteDetailsResponseProductsInnerPrice) SetExtendedQuotePrice(v float32) {
	o.ExtendedQuotePrice = &v
}

// GetDiscountOffList returns the DiscountOffList field value if set, zero value otherwise.
func (o *QuoteDetailsResponseProductsInnerPrice) GetDiscountOffList() string {
	if o == nil || IsNil(o.DiscountOffList) {
		var ret string
		return ret
	}
	return *o.DiscountOffList
}

// GetDiscountOffListOk returns a tuple with the DiscountOffList field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuoteDetailsResponseProductsInnerPrice) GetDiscountOffListOk() (*string, bool) {
	if o == nil || IsNil(o.DiscountOffList) {
		return nil, false
	}
	return o.DiscountOffList, true
}

// HasDiscountOffList returns a boolean if a field has been set.
func (o *QuoteDetailsResponseProductsInnerPrice) HasDiscountOffList() bool {
	if o != nil && !IsNil(o.DiscountOffList) {
		return true
	}

	return false
}

// SetDiscountOffList gets a reference to the given string and assigns it to the DiscountOffList field.
func (o *QuoteDetailsResponseProductsInnerPrice) SetDiscountOffList(v string) {
	o.DiscountOffList = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *QuoteDetailsResponseProductsInnerPrice) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuoteDetailsResponseProductsInnerPrice) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *QuoteDetailsResponseProductsInnerPrice) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *QuoteDetailsResponseProductsInnerPrice) SetType(v string) {
	o.Type = &v
}

// GetRecurringPriceModel returns the RecurringPriceModel field value if set, zero value otherwise.
func (o *QuoteDetailsResponseProductsInnerPrice) GetRecurringPriceModel() string {
	if o == nil || IsNil(o.RecurringPriceModel) {
		var ret string
		return ret
	}
	return *o.RecurringPriceModel
}

// GetRecurringPriceModelOk returns a tuple with the RecurringPriceModel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuoteDetailsResponseProductsInnerPrice) GetRecurringPriceModelOk() (*string, bool) {
	if o == nil || IsNil(o.RecurringPriceModel) {
		return nil, false
	}
	return o.RecurringPriceModel, true
}

// HasRecurringPriceModel returns a boolean if a field has been set.
func (o *QuoteDetailsResponseProductsInnerPrice) HasRecurringPriceModel() bool {
	if o != nil && !IsNil(o.RecurringPriceModel) {
		return true
	}

	return false
}

// SetRecurringPriceModel gets a reference to the given string and assigns it to the RecurringPriceModel field.
func (o *QuoteDetailsResponseProductsInnerPrice) SetRecurringPriceModel(v string) {
	o.RecurringPriceModel = &v
}

// GetUnitOfMeasure returns the UnitOfMeasure field value if set, zero value otherwise.
func (o *QuoteDetailsResponseProductsInnerPrice) GetUnitOfMeasure() string {
	if o == nil || IsNil(o.UnitOfMeasure) {
		var ret string
		return ret
	}
	return *o.UnitOfMeasure
}

// GetUnitOfMeasureOk returns a tuple with the UnitOfMeasure field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuoteDetailsResponseProductsInnerPrice) GetUnitOfMeasureOk() (*string, bool) {
	if o == nil || IsNil(o.UnitOfMeasure) {
		return nil, false
	}
	return o.UnitOfMeasure, true
}

// HasUnitOfMeasure returns a boolean if a field has been set.
func (o *QuoteDetailsResponseProductsInnerPrice) HasUnitOfMeasure() bool {
	if o != nil && !IsNil(o.UnitOfMeasure) {
		return true
	}

	return false
}

// SetUnitOfMeasure gets a reference to the given string and assigns it to the UnitOfMeasure field.
func (o *QuoteDetailsResponseProductsInnerPrice) SetUnitOfMeasure(v string) {
	o.UnitOfMeasure = &v
}

// GetTax returns the Tax field value if set, zero value otherwise.
func (o *QuoteDetailsResponseProductsInnerPrice) GetTax() string {
	if o == nil || IsNil(o.Tax) {
		var ret string
		return ret
	}
	return *o.Tax
}

// GetTaxOk returns a tuple with the Tax field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuoteDetailsResponseProductsInnerPrice) GetTaxOk() (*string, bool) {
	if o == nil || IsNil(o.Tax) {
		return nil, false
	}
	return o.Tax, true
}

// HasTax returns a boolean if a field has been set.
func (o *QuoteDetailsResponseProductsInnerPrice) HasTax() bool {
	if o != nil && !IsNil(o.Tax) {
		return true
	}

	return false
}

// SetTax gets a reference to the given string and assigns it to the Tax field.
func (o *QuoteDetailsResponseProductsInnerPrice) SetTax(v string) {
	o.Tax = &v
}

// GetExtrafees returns the Extrafees field value if set, zero value otherwise.
func (o *QuoteDetailsResponseProductsInnerPrice) GetExtrafees() float32 {
	if o == nil || IsNil(o.Extrafees) {
		var ret float32
		return ret
	}
	return *o.Extrafees
}

// GetExtrafeesOk returns a tuple with the Extrafees field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuoteDetailsResponseProductsInnerPrice) GetExtrafeesOk() (*float32, bool) {
	if o == nil || IsNil(o.Extrafees) {
		return nil, false
	}
	return o.Extrafees, true
}

// HasExtrafees returns a boolean if a field has been set.
func (o *QuoteDetailsResponseProductsInnerPrice) HasExtrafees() bool {
	if o != nil && !IsNil(o.Extrafees) {
		return true
	}

	return false
}

// SetExtrafees gets a reference to the given float32 and assigns it to the Extrafees field.
func (o *QuoteDetailsResponseProductsInnerPrice) SetExtrafees(v float32) {
	o.Extrafees = &v
}

// GetExtraFeesDetails returns the ExtraFeesDetails field value if set, zero value otherwise.
func (o *QuoteDetailsResponseProductsInnerPrice) GetExtraFeesDetails() []QuoteDetailsResponseProductsInnerPriceExtraFeesDetailsInner {
	if o == nil || IsNil(o.ExtraFeesDetails) {
		var ret []QuoteDetailsResponseProductsInnerPriceExtraFeesDetailsInner
		return ret
	}
	return o.ExtraFeesDetails
}

// GetExtraFeesDetailsOk returns a tuple with the ExtraFeesDetails field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuoteDetailsResponseProductsInnerPrice) GetExtraFeesDetailsOk() ([]QuoteDetailsResponseProductsInnerPriceExtraFeesDetailsInner, bool) {
	if o == nil || IsNil(o.ExtraFeesDetails) {
		return nil, false
	}
	return o.ExtraFeesDetails, true
}

// HasExtraFeesDetails returns a boolean if a field has been set.
func (o *QuoteDetailsResponseProductsInnerPrice) HasExtraFeesDetails() bool {
	if o != nil && !IsNil(o.ExtraFeesDetails) {
		return true
	}

	return false
}

// SetExtraFeesDetails gets a reference to the given []QuoteDetailsResponseProductsInnerPriceExtraFeesDetailsInner and assigns it to the ExtraFeesDetails field.
func (o *QuoteDetailsResponseProductsInnerPrice) SetExtraFeesDetails(v []QuoteDetailsResponseProductsInnerPriceExtraFeesDetailsInner) {
	o.ExtraFeesDetails = v
}

// GetDiscounts returns the Discounts field value if set, zero value otherwise.
func (o *QuoteDetailsResponseProductsInnerPrice) GetDiscounts() []QuoteDetailsResponseProductsInnerPriceDiscountsInner {
	if o == nil || IsNil(o.Discounts) {
		var ret []QuoteDetailsResponseProductsInnerPriceDiscountsInner
		return ret
	}
	return o.Discounts
}

// GetDiscountsOk returns a tuple with the Discounts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuoteDetailsResponseProductsInnerPrice) GetDiscountsOk() ([]QuoteDetailsResponseProductsInnerPriceDiscountsInner, bool) {
	if o == nil || IsNil(o.Discounts) {
		return nil, false
	}
	return o.Discounts, true
}

// HasDiscounts returns a boolean if a field has been set.
func (o *QuoteDetailsResponseProductsInnerPrice) HasDiscounts() bool {
	if o != nil && !IsNil(o.Discounts) {
		return true
	}

	return false
}

// SetDiscounts gets a reference to the given []QuoteDetailsResponseProductsInnerPriceDiscountsInner and assigns it to the Discounts field.
func (o *QuoteDetailsResponseProductsInnerPrice) SetDiscounts(v []QuoteDetailsResponseProductsInnerPriceDiscountsInner) {
	o.Discounts = v
}

func (o QuoteDetailsResponseProductsInnerPrice) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o QuoteDetailsResponseProductsInnerPrice) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.QuotePrice) {
		toSerialize["quotePrice"] = o.QuotePrice
	}
	if !IsNil(o.Msrp) {
		toSerialize["msrp"] = o.Msrp
	}
	if !IsNil(o.ExtendedMsrp) {
		toSerialize["extendedMsrp"] = o.ExtendedMsrp
	}
	if !IsNil(o.ExtendedQuotePrice) {
		toSerialize["extendedQuotePrice"] = o.ExtendedQuotePrice
	}
	if !IsNil(o.DiscountOffList) {
		toSerialize["discountOffList"] = o.DiscountOffList
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.RecurringPriceModel) {
		toSerialize["recurringPriceModel"] = o.RecurringPriceModel
	}
	if !IsNil(o.UnitOfMeasure) {
		toSerialize["unitOfMeasure"] = o.UnitOfMeasure
	}
	if !IsNil(o.Tax) {
		toSerialize["tax"] = o.Tax
	}
	if !IsNil(o.Extrafees) {
		toSerialize["extrafees"] = o.Extrafees
	}
	if !IsNil(o.ExtraFeesDetails) {
		toSerialize["extraFeesDetails"] = o.ExtraFeesDetails
	}
	if !IsNil(o.Discounts) {
		toSerialize["discounts"] = o.Discounts
	}
	return toSerialize, nil
}

type NullableQuoteDetailsResponseProductsInnerPrice struct {
	value *QuoteDetailsResponseProductsInnerPrice
	isSet bool
}

func (v NullableQuoteDetailsResponseProductsInnerPrice) Get() *QuoteDetailsResponseProductsInnerPrice {
	return v.value
}

func (v *NullableQuoteDetailsResponseProductsInnerPrice) Set(val *QuoteDetailsResponseProductsInnerPrice) {
	v.value = val
	v.isSet = true
}

func (v NullableQuoteDetailsResponseProductsInnerPrice) IsSet() bool {
	return v.isSet
}

func (v *NullableQuoteDetailsResponseProductsInnerPrice) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableQuoteDetailsResponseProductsInnerPrice(val *QuoteDetailsResponseProductsInnerPrice) *NullableQuoteDetailsResponseProductsInnerPrice {
	return &NullableQuoteDetailsResponseProductsInnerPrice{value: val, isSet: true}
}

func (v NullableQuoteDetailsResponseProductsInnerPrice) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableQuoteDetailsResponseProductsInnerPrice) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


