/*
Reseller API Documentation

For Resellers. <br> Who are looking to Innovate with Ingram Micro's API SolutionsAutomate your eCommerce with our offering of APIs and Webhooks to create a seamless experience for your customers.

API version: 6.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package xi-sdk-resellers-go

import (
	"encoding/json"
)

// checks if the ProductSearchResponseServiceresponseProductsearchresponseInnerPartnumbersInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProductSearchResponseServiceresponseProductsearchresponseInnerPartnumbersInner{}

// ProductSearchResponseServiceresponseProductsearchresponseInnerPartnumbersInner struct for ProductSearchResponseServiceresponseProductsearchresponseInnerPartnumbersInner
type ProductSearchResponseServiceresponseProductsearchresponseInnerPartnumbersInner struct {
	// Ingram Part Number
	Ingrampartnumber *string `json:"ingrampartnumber,omitempty"`
	// Vendor or Manufacturer Part Number
	Manufacturerpartnumber *string `json:"manufacturerpartnumber,omitempty"`
	// UPC
	Upccode *string `json:"upccode,omitempty"`
	// Product description
	Productdescription *string `json:"productdescription,omitempty"`
	Currency *string `json:"currency,omitempty"`
	Haswarranty *string `json:"haswarranty,omitempty"`
}

// NewProductSearchResponseServiceresponseProductsearchresponseInnerPartnumbersInner instantiates a new ProductSearchResponseServiceresponseProductsearchresponseInnerPartnumbersInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProductSearchResponseServiceresponseProductsearchresponseInnerPartnumbersInner() *ProductSearchResponseServiceresponseProductsearchresponseInnerPartnumbersInner {
	this := ProductSearchResponseServiceresponseProductsearchresponseInnerPartnumbersInner{}
	return &this
}

// NewProductSearchResponseServiceresponseProductsearchresponseInnerPartnumbersInnerWithDefaults instantiates a new ProductSearchResponseServiceresponseProductsearchresponseInnerPartnumbersInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProductSearchResponseServiceresponseProductsearchresponseInnerPartnumbersInnerWithDefaults() *ProductSearchResponseServiceresponseProductsearchresponseInnerPartnumbersInner {
	this := ProductSearchResponseServiceresponseProductsearchresponseInnerPartnumbersInner{}
	return &this
}

// GetIngrampartnumber returns the Ingrampartnumber field value if set, zero value otherwise.
func (o *ProductSearchResponseServiceresponseProductsearchresponseInnerPartnumbersInner) GetIngrampartnumber() string {
	if o == nil || IsNil(o.Ingrampartnumber) {
		var ret string
		return ret
	}
	return *o.Ingrampartnumber
}

// GetIngrampartnumberOk returns a tuple with the Ingrampartnumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductSearchResponseServiceresponseProductsearchresponseInnerPartnumbersInner) GetIngrampartnumberOk() (*string, bool) {
	if o == nil || IsNil(o.Ingrampartnumber) {
		return nil, false
	}
	return o.Ingrampartnumber, true
}

// HasIngrampartnumber returns a boolean if a field has been set.
func (o *ProductSearchResponseServiceresponseProductsearchresponseInnerPartnumbersInner) HasIngrampartnumber() bool {
	if o != nil && !IsNil(o.Ingrampartnumber) {
		return true
	}

	return false
}

// SetIngrampartnumber gets a reference to the given string and assigns it to the Ingrampartnumber field.
func (o *ProductSearchResponseServiceresponseProductsearchresponseInnerPartnumbersInner) SetIngrampartnumber(v string) {
	o.Ingrampartnumber = &v
}

// GetManufacturerpartnumber returns the Manufacturerpartnumber field value if set, zero value otherwise.
func (o *ProductSearchResponseServiceresponseProductsearchresponseInnerPartnumbersInner) GetManufacturerpartnumber() string {
	if o == nil || IsNil(o.Manufacturerpartnumber) {
		var ret string
		return ret
	}
	return *o.Manufacturerpartnumber
}

// GetManufacturerpartnumberOk returns a tuple with the Manufacturerpartnumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductSearchResponseServiceresponseProductsearchresponseInnerPartnumbersInner) GetManufacturerpartnumberOk() (*string, bool) {
	if o == nil || IsNil(o.Manufacturerpartnumber) {
		return nil, false
	}
	return o.Manufacturerpartnumber, true
}

// HasManufacturerpartnumber returns a boolean if a field has been set.
func (o *ProductSearchResponseServiceresponseProductsearchresponseInnerPartnumbersInner) HasManufacturerpartnumber() bool {
	if o != nil && !IsNil(o.Manufacturerpartnumber) {
		return true
	}

	return false
}

// SetManufacturerpartnumber gets a reference to the given string and assigns it to the Manufacturerpartnumber field.
func (o *ProductSearchResponseServiceresponseProductsearchresponseInnerPartnumbersInner) SetManufacturerpartnumber(v string) {
	o.Manufacturerpartnumber = &v
}

// GetUpccode returns the Upccode field value if set, zero value otherwise.
func (o *ProductSearchResponseServiceresponseProductsearchresponseInnerPartnumbersInner) GetUpccode() string {
	if o == nil || IsNil(o.Upccode) {
		var ret string
		return ret
	}
	return *o.Upccode
}

// GetUpccodeOk returns a tuple with the Upccode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductSearchResponseServiceresponseProductsearchresponseInnerPartnumbersInner) GetUpccodeOk() (*string, bool) {
	if o == nil || IsNil(o.Upccode) {
		return nil, false
	}
	return o.Upccode, true
}

// HasUpccode returns a boolean if a field has been set.
func (o *ProductSearchResponseServiceresponseProductsearchresponseInnerPartnumbersInner) HasUpccode() bool {
	if o != nil && !IsNil(o.Upccode) {
		return true
	}

	return false
}

// SetUpccode gets a reference to the given string and assigns it to the Upccode field.
func (o *ProductSearchResponseServiceresponseProductsearchresponseInnerPartnumbersInner) SetUpccode(v string) {
	o.Upccode = &v
}

// GetProductdescription returns the Productdescription field value if set, zero value otherwise.
func (o *ProductSearchResponseServiceresponseProductsearchresponseInnerPartnumbersInner) GetProductdescription() string {
	if o == nil || IsNil(o.Productdescription) {
		var ret string
		return ret
	}
	return *o.Productdescription
}

// GetProductdescriptionOk returns a tuple with the Productdescription field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductSearchResponseServiceresponseProductsearchresponseInnerPartnumbersInner) GetProductdescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Productdescription) {
		return nil, false
	}
	return o.Productdescription, true
}

// HasProductdescription returns a boolean if a field has been set.
func (o *ProductSearchResponseServiceresponseProductsearchresponseInnerPartnumbersInner) HasProductdescription() bool {
	if o != nil && !IsNil(o.Productdescription) {
		return true
	}

	return false
}

// SetProductdescription gets a reference to the given string and assigns it to the Productdescription field.
func (o *ProductSearchResponseServiceresponseProductsearchresponseInnerPartnumbersInner) SetProductdescription(v string) {
	o.Productdescription = &v
}

// GetCurrency returns the Currency field value if set, zero value otherwise.
func (o *ProductSearchResponseServiceresponseProductsearchresponseInnerPartnumbersInner) GetCurrency() string {
	if o == nil || IsNil(o.Currency) {
		var ret string
		return ret
	}
	return *o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductSearchResponseServiceresponseProductsearchresponseInnerPartnumbersInner) GetCurrencyOk() (*string, bool) {
	if o == nil || IsNil(o.Currency) {
		return nil, false
	}
	return o.Currency, true
}

// HasCurrency returns a boolean if a field has been set.
func (o *ProductSearchResponseServiceresponseProductsearchresponseInnerPartnumbersInner) HasCurrency() bool {
	if o != nil && !IsNil(o.Currency) {
		return true
	}

	return false
}

// SetCurrency gets a reference to the given string and assigns it to the Currency field.
func (o *ProductSearchResponseServiceresponseProductsearchresponseInnerPartnumbersInner) SetCurrency(v string) {
	o.Currency = &v
}

// GetHaswarranty returns the Haswarranty field value if set, zero value otherwise.
func (o *ProductSearchResponseServiceresponseProductsearchresponseInnerPartnumbersInner) GetHaswarranty() string {
	if o == nil || IsNil(o.Haswarranty) {
		var ret string
		return ret
	}
	return *o.Haswarranty
}

// GetHaswarrantyOk returns a tuple with the Haswarranty field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductSearchResponseServiceresponseProductsearchresponseInnerPartnumbersInner) GetHaswarrantyOk() (*string, bool) {
	if o == nil || IsNil(o.Haswarranty) {
		return nil, false
	}
	return o.Haswarranty, true
}

// HasHaswarranty returns a boolean if a field has been set.
func (o *ProductSearchResponseServiceresponseProductsearchresponseInnerPartnumbersInner) HasHaswarranty() bool {
	if o != nil && !IsNil(o.Haswarranty) {
		return true
	}

	return false
}

// SetHaswarranty gets a reference to the given string and assigns it to the Haswarranty field.
func (o *ProductSearchResponseServiceresponseProductsearchresponseInnerPartnumbersInner) SetHaswarranty(v string) {
	o.Haswarranty = &v
}

func (o ProductSearchResponseServiceresponseProductsearchresponseInnerPartnumbersInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProductSearchResponseServiceresponseProductsearchresponseInnerPartnumbersInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Ingrampartnumber) {
		toSerialize["ingrampartnumber"] = o.Ingrampartnumber
	}
	if !IsNil(o.Manufacturerpartnumber) {
		toSerialize["manufacturerpartnumber"] = o.Manufacturerpartnumber
	}
	if !IsNil(o.Upccode) {
		toSerialize["upccode"] = o.Upccode
	}
	if !IsNil(o.Productdescription) {
		toSerialize["productdescription"] = o.Productdescription
	}
	if !IsNil(o.Currency) {
		toSerialize["currency"] = o.Currency
	}
	if !IsNil(o.Haswarranty) {
		toSerialize["haswarranty"] = o.Haswarranty
	}
	return toSerialize, nil
}

type NullableProductSearchResponseServiceresponseProductsearchresponseInnerPartnumbersInner struct {
	value *ProductSearchResponseServiceresponseProductsearchresponseInnerPartnumbersInner
	isSet bool
}

func (v NullableProductSearchResponseServiceresponseProductsearchresponseInnerPartnumbersInner) Get() *ProductSearchResponseServiceresponseProductsearchresponseInnerPartnumbersInner {
	return v.value
}

func (v *NullableProductSearchResponseServiceresponseProductsearchresponseInnerPartnumbersInner) Set(val *ProductSearchResponseServiceresponseProductsearchresponseInnerPartnumbersInner) {
	v.value = val
	v.isSet = true
}

func (v NullableProductSearchResponseServiceresponseProductsearchresponseInnerPartnumbersInner) IsSet() bool {
	return v.isSet
}

func (v *NullableProductSearchResponseServiceresponseProductsearchresponseInnerPartnumbersInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProductSearchResponseServiceresponseProductsearchresponseInnerPartnumbersInner(val *ProductSearchResponseServiceresponseProductsearchresponseInnerPartnumbersInner) *NullableProductSearchResponseServiceresponseProductsearchresponseInnerPartnumbersInner {
	return &NullableProductSearchResponseServiceresponseProductsearchresponseInnerPartnumbersInner{value: val, isSet: true}
}

func (v NullableProductSearchResponseServiceresponseProductsearchresponseInnerPartnumbersInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProductSearchResponseServiceresponseProductsearchresponseInnerPartnumbersInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


