/*
Reseller API Documentation

For Resellers. <br> Who are looking to Innovate with Ingram Micro's API SolutionsAutomate your eCommerce with our offering of APIs and Webhooks to create a seamless experience for your customers.

API version: 6.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package xi-sdk-resellers-go

import (
	"encoding/json"
)

// checks if the QuoteListResponseQuoteSearchResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &QuoteListResponseQuoteSearchResponse{}

// QuoteListResponseQuoteSearchResponse struct for QuoteListResponseQuoteSearchResponse
type QuoteListResponseQuoteSearchResponse struct {
	ResponsePreamble *QuoteListResponseQuoteSearchResponseResponsePreamble `json:"responsePreamble,omitempty"`
	QuoteList []QuoteListResponseQuoteSearchResponseQuoteListInner `json:"quoteList,omitempty"`
	// Total count of quotes retrieved in the request response.
	TotalCount *int32 `json:"totalCount,omitempty"`
}

// NewQuoteListResponseQuoteSearchResponse instantiates a new QuoteListResponseQuoteSearchResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewQuoteListResponseQuoteSearchResponse() *QuoteListResponseQuoteSearchResponse {
	this := QuoteListResponseQuoteSearchResponse{}
	return &this
}

// NewQuoteListResponseQuoteSearchResponseWithDefaults instantiates a new QuoteListResponseQuoteSearchResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewQuoteListResponseQuoteSearchResponseWithDefaults() *QuoteListResponseQuoteSearchResponse {
	this := QuoteListResponseQuoteSearchResponse{}
	return &this
}

// GetResponsePreamble returns the ResponsePreamble field value if set, zero value otherwise.
func (o *QuoteListResponseQuoteSearchResponse) GetResponsePreamble() QuoteListResponseQuoteSearchResponseResponsePreamble {
	if o == nil || IsNil(o.ResponsePreamble) {
		var ret QuoteListResponseQuoteSearchResponseResponsePreamble
		return ret
	}
	return *o.ResponsePreamble
}

// GetResponsePreambleOk returns a tuple with the ResponsePreamble field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuoteListResponseQuoteSearchResponse) GetResponsePreambleOk() (*QuoteListResponseQuoteSearchResponseResponsePreamble, bool) {
	if o == nil || IsNil(o.ResponsePreamble) {
		return nil, false
	}
	return o.ResponsePreamble, true
}

// HasResponsePreamble returns a boolean if a field has been set.
func (o *QuoteListResponseQuoteSearchResponse) HasResponsePreamble() bool {
	if o != nil && !IsNil(o.ResponsePreamble) {
		return true
	}

	return false
}

// SetResponsePreamble gets a reference to the given QuoteListResponseQuoteSearchResponseResponsePreamble and assigns it to the ResponsePreamble field.
func (o *QuoteListResponseQuoteSearchResponse) SetResponsePreamble(v QuoteListResponseQuoteSearchResponseResponsePreamble) {
	o.ResponsePreamble = &v
}

// GetQuoteList returns the QuoteList field value if set, zero value otherwise.
func (o *QuoteListResponseQuoteSearchResponse) GetQuoteList() []QuoteListResponseQuoteSearchResponseQuoteListInner {
	if o == nil || IsNil(o.QuoteList) {
		var ret []QuoteListResponseQuoteSearchResponseQuoteListInner
		return ret
	}
	return o.QuoteList
}

// GetQuoteListOk returns a tuple with the QuoteList field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuoteListResponseQuoteSearchResponse) GetQuoteListOk() ([]QuoteListResponseQuoteSearchResponseQuoteListInner, bool) {
	if o == nil || IsNil(o.QuoteList) {
		return nil, false
	}
	return o.QuoteList, true
}

// HasQuoteList returns a boolean if a field has been set.
func (o *QuoteListResponseQuoteSearchResponse) HasQuoteList() bool {
	if o != nil && !IsNil(o.QuoteList) {
		return true
	}

	return false
}

// SetQuoteList gets a reference to the given []QuoteListResponseQuoteSearchResponseQuoteListInner and assigns it to the QuoteList field.
func (o *QuoteListResponseQuoteSearchResponse) SetQuoteList(v []QuoteListResponseQuoteSearchResponseQuoteListInner) {
	o.QuoteList = v
}

// GetTotalCount returns the TotalCount field value if set, zero value otherwise.
func (o *QuoteListResponseQuoteSearchResponse) GetTotalCount() int32 {
	if o == nil || IsNil(o.TotalCount) {
		var ret int32
		return ret
	}
	return *o.TotalCount
}

// GetTotalCountOk returns a tuple with the TotalCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuoteListResponseQuoteSearchResponse) GetTotalCountOk() (*int32, bool) {
	if o == nil || IsNil(o.TotalCount) {
		return nil, false
	}
	return o.TotalCount, true
}

// HasTotalCount returns a boolean if a field has been set.
func (o *QuoteListResponseQuoteSearchResponse) HasTotalCount() bool {
	if o != nil && !IsNil(o.TotalCount) {
		return true
	}

	return false
}

// SetTotalCount gets a reference to the given int32 and assigns it to the TotalCount field.
func (o *QuoteListResponseQuoteSearchResponse) SetTotalCount(v int32) {
	o.TotalCount = &v
}

func (o QuoteListResponseQuoteSearchResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o QuoteListResponseQuoteSearchResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ResponsePreamble) {
		toSerialize["responsePreamble"] = o.ResponsePreamble
	}
	if !IsNil(o.QuoteList) {
		toSerialize["quoteList"] = o.QuoteList
	}
	if !IsNil(o.TotalCount) {
		toSerialize["totalCount"] = o.TotalCount
	}
	return toSerialize, nil
}

type NullableQuoteListResponseQuoteSearchResponse struct {
	value *QuoteListResponseQuoteSearchResponse
	isSet bool
}

func (v NullableQuoteListResponseQuoteSearchResponse) Get() *QuoteListResponseQuoteSearchResponse {
	return v.value
}

func (v *NullableQuoteListResponseQuoteSearchResponse) Set(val *QuoteListResponseQuoteSearchResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableQuoteListResponseQuoteSearchResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableQuoteListResponseQuoteSearchResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableQuoteListResponseQuoteSearchResponse(val *QuoteListResponseQuoteSearchResponse) *NullableQuoteListResponseQuoteSearchResponse {
	return &NullableQuoteListResponseQuoteSearchResponse{value: val, isSet: true}
}

func (v NullableQuoteListResponseQuoteSearchResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableQuoteListResponseQuoteSearchResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


