/*
XI Sdk Resellers

For Resellers. Who are looking to Innovate with Ingram Micro's API SolutionsAutomate your eCommerce with our offering of APIs and Webhooks to create a seamless experience for your customers.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package xi_sdk_resellers

import (
	"encoding/json"
)

// checks if the QuoteDetailsResponseProductsInnerPrice type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &QuoteDetailsResponseProductsInnerPrice{}

// QuoteDetailsResponseProductsInnerPrice struct for QuoteDetailsResponseProductsInnerPrice
type QuoteDetailsResponseProductsInnerPrice struct {
	// Ingram Micro quoted price specific to the reseller and quote.
	QuotePrice *int32 `json:"quotePrice,omitempty"`
	// Manufacturer Suggested Retail Price
	Msrp *int32 `json:"msrp,omitempty"`
	// Extended MSRP - Manufacturer Suggested Retail Price X Quantity
	ExtendedMsrp *int32 `json:"extendedMsrp,omitempty"`
	// Extended reseller quoted price (cost to reseller) X Quantity
	ExtendedQuotePrice *int32 `json:"extendedQuotePrice,omitempty"`
	// Discount off list percentage extended
	DiscountOffList *string `json:"discountOffList,omitempty"`
	Vendorprice *float32 `json:"vendorprice,omitempty"`
	Extendedvendorprice *float32 `json:"extendedvendorprice,omitempty"`
	TotalVisibleReserveQuantity *int32 `json:"totalVisibleReserveQuantity,omitempty"`
	Type *string `json:"type,omitempty"`
	RecurringPriceModel *string `json:"recurringPriceModel,omitempty"`
}

// NewQuoteDetailsResponseProductsInnerPrice instantiates a new QuoteDetailsResponseProductsInnerPrice object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewQuoteDetailsResponseProductsInnerPrice() *QuoteDetailsResponseProductsInnerPrice {
	this := QuoteDetailsResponseProductsInnerPrice{}
	return &this
}

// NewQuoteDetailsResponseProductsInnerPriceWithDefaults instantiates a new QuoteDetailsResponseProductsInnerPrice object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewQuoteDetailsResponseProductsInnerPriceWithDefaults() *QuoteDetailsResponseProductsInnerPrice {
	this := QuoteDetailsResponseProductsInnerPrice{}
	return &this
}

// GetQuotePrice returns the QuotePrice field value if set, zero value otherwise.
func (o *QuoteDetailsResponseProductsInnerPrice) GetQuotePrice() int32 {
	if o == nil || IsNil(o.QuotePrice) {
		var ret int32
		return ret
	}
	return *o.QuotePrice
}

// GetQuotePriceOk returns a tuple with the QuotePrice field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuoteDetailsResponseProductsInnerPrice) GetQuotePriceOk() (*int32, bool) {
	if o == nil || IsNil(o.QuotePrice) {
		return nil, false
	}
	return o.QuotePrice, true
}

// HasQuotePrice returns a boolean if a field has been set.
func (o *QuoteDetailsResponseProductsInnerPrice) HasQuotePrice() bool {
	if o != nil && !IsNil(o.QuotePrice) {
		return true
	}

	return false
}

// SetQuotePrice gets a reference to the given int32 and assigns it to the QuotePrice field.
func (o *QuoteDetailsResponseProductsInnerPrice) SetQuotePrice(v int32) {
	o.QuotePrice = &v
}

// GetMsrp returns the Msrp field value if set, zero value otherwise.
func (o *QuoteDetailsResponseProductsInnerPrice) GetMsrp() int32 {
	if o == nil || IsNil(o.Msrp) {
		var ret int32
		return ret
	}
	return *o.Msrp
}

// GetMsrpOk returns a tuple with the Msrp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuoteDetailsResponseProductsInnerPrice) GetMsrpOk() (*int32, bool) {
	if o == nil || IsNil(o.Msrp) {
		return nil, false
	}
	return o.Msrp, true
}

// HasMsrp returns a boolean if a field has been set.
func (o *QuoteDetailsResponseProductsInnerPrice) HasMsrp() bool {
	if o != nil && !IsNil(o.Msrp) {
		return true
	}

	return false
}

// SetMsrp gets a reference to the given int32 and assigns it to the Msrp field.
func (o *QuoteDetailsResponseProductsInnerPrice) SetMsrp(v int32) {
	o.Msrp = &v
}

// GetExtendedMsrp returns the ExtendedMsrp field value if set, zero value otherwise.
func (o *QuoteDetailsResponseProductsInnerPrice) GetExtendedMsrp() int32 {
	if o == nil || IsNil(o.ExtendedMsrp) {
		var ret int32
		return ret
	}
	return *o.ExtendedMsrp
}

// GetExtendedMsrpOk returns a tuple with the ExtendedMsrp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuoteDetailsResponseProductsInnerPrice) GetExtendedMsrpOk() (*int32, bool) {
	if o == nil || IsNil(o.ExtendedMsrp) {
		return nil, false
	}
	return o.ExtendedMsrp, true
}

// HasExtendedMsrp returns a boolean if a field has been set.
func (o *QuoteDetailsResponseProductsInnerPrice) HasExtendedMsrp() bool {
	if o != nil && !IsNil(o.ExtendedMsrp) {
		return true
	}

	return false
}

// SetExtendedMsrp gets a reference to the given int32 and assigns it to the ExtendedMsrp field.
func (o *QuoteDetailsResponseProductsInnerPrice) SetExtendedMsrp(v int32) {
	o.ExtendedMsrp = &v
}

// GetExtendedQuotePrice returns the ExtendedQuotePrice field value if set, zero value otherwise.
func (o *QuoteDetailsResponseProductsInnerPrice) GetExtendedQuotePrice() int32 {
	if o == nil || IsNil(o.ExtendedQuotePrice) {
		var ret int32
		return ret
	}
	return *o.ExtendedQuotePrice
}

// GetExtendedQuotePriceOk returns a tuple with the ExtendedQuotePrice field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuoteDetailsResponseProductsInnerPrice) GetExtendedQuotePriceOk() (*int32, bool) {
	if o == nil || IsNil(o.ExtendedQuotePrice) {
		return nil, false
	}
	return o.ExtendedQuotePrice, true
}

// HasExtendedQuotePrice returns a boolean if a field has been set.
func (o *QuoteDetailsResponseProductsInnerPrice) HasExtendedQuotePrice() bool {
	if o != nil && !IsNil(o.ExtendedQuotePrice) {
		return true
	}

	return false
}

// SetExtendedQuotePrice gets a reference to the given int32 and assigns it to the ExtendedQuotePrice field.
func (o *QuoteDetailsResponseProductsInnerPrice) SetExtendedQuotePrice(v int32) {
	o.ExtendedQuotePrice = &v
}

// GetDiscountOffList returns the DiscountOffList field value if set, zero value otherwise.
func (o *QuoteDetailsResponseProductsInnerPrice) GetDiscountOffList() string {
	if o == nil || IsNil(o.DiscountOffList) {
		var ret string
		return ret
	}
	return *o.DiscountOffList
}

// GetDiscountOffListOk returns a tuple with the DiscountOffList field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuoteDetailsResponseProductsInnerPrice) GetDiscountOffListOk() (*string, bool) {
	if o == nil || IsNil(o.DiscountOffList) {
		return nil, false
	}
	return o.DiscountOffList, true
}

// HasDiscountOffList returns a boolean if a field has been set.
func (o *QuoteDetailsResponseProductsInnerPrice) HasDiscountOffList() bool {
	if o != nil && !IsNil(o.DiscountOffList) {
		return true
	}

	return false
}

// SetDiscountOffList gets a reference to the given string and assigns it to the DiscountOffList field.
func (o *QuoteDetailsResponseProductsInnerPrice) SetDiscountOffList(v string) {
	o.DiscountOffList = &v
}

// GetVendorprice returns the Vendorprice field value if set, zero value otherwise.
func (o *QuoteDetailsResponseProductsInnerPrice) GetVendorprice() float32 {
	if o == nil || IsNil(o.Vendorprice) {
		var ret float32
		return ret
	}
	return *o.Vendorprice
}

// GetVendorpriceOk returns a tuple with the Vendorprice field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuoteDetailsResponseProductsInnerPrice) GetVendorpriceOk() (*float32, bool) {
	if o == nil || IsNil(o.Vendorprice) {
		return nil, false
	}
	return o.Vendorprice, true
}

// HasVendorprice returns a boolean if a field has been set.
func (o *QuoteDetailsResponseProductsInnerPrice) HasVendorprice() bool {
	if o != nil && !IsNil(o.Vendorprice) {
		return true
	}

	return false
}

// SetVendorprice gets a reference to the given float32 and assigns it to the Vendorprice field.
func (o *QuoteDetailsResponseProductsInnerPrice) SetVendorprice(v float32) {
	o.Vendorprice = &v
}

// GetExtendedvendorprice returns the Extendedvendorprice field value if set, zero value otherwise.
func (o *QuoteDetailsResponseProductsInnerPrice) GetExtendedvendorprice() float32 {
	if o == nil || IsNil(o.Extendedvendorprice) {
		var ret float32
		return ret
	}
	return *o.Extendedvendorprice
}

// GetExtendedvendorpriceOk returns a tuple with the Extendedvendorprice field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuoteDetailsResponseProductsInnerPrice) GetExtendedvendorpriceOk() (*float32, bool) {
	if o == nil || IsNil(o.Extendedvendorprice) {
		return nil, false
	}
	return o.Extendedvendorprice, true
}

// HasExtendedvendorprice returns a boolean if a field has been set.
func (o *QuoteDetailsResponseProductsInnerPrice) HasExtendedvendorprice() bool {
	if o != nil && !IsNil(o.Extendedvendorprice) {
		return true
	}

	return false
}

// SetExtendedvendorprice gets a reference to the given float32 and assigns it to the Extendedvendorprice field.
func (o *QuoteDetailsResponseProductsInnerPrice) SetExtendedvendorprice(v float32) {
	o.Extendedvendorprice = &v
}

// GetTotalVisibleReserveQuantity returns the TotalVisibleReserveQuantity field value if set, zero value otherwise.
func (o *QuoteDetailsResponseProductsInnerPrice) GetTotalVisibleReserveQuantity() int32 {
	if o == nil || IsNil(o.TotalVisibleReserveQuantity) {
		var ret int32
		return ret
	}
	return *o.TotalVisibleReserveQuantity
}

// GetTotalVisibleReserveQuantityOk returns a tuple with the TotalVisibleReserveQuantity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuoteDetailsResponseProductsInnerPrice) GetTotalVisibleReserveQuantityOk() (*int32, bool) {
	if o == nil || IsNil(o.TotalVisibleReserveQuantity) {
		return nil, false
	}
	return o.TotalVisibleReserveQuantity, true
}

// HasTotalVisibleReserveQuantity returns a boolean if a field has been set.
func (o *QuoteDetailsResponseProductsInnerPrice) HasTotalVisibleReserveQuantity() bool {
	if o != nil && !IsNil(o.TotalVisibleReserveQuantity) {
		return true
	}

	return false
}

// SetTotalVisibleReserveQuantity gets a reference to the given int32 and assigns it to the TotalVisibleReserveQuantity field.
func (o *QuoteDetailsResponseProductsInnerPrice) SetTotalVisibleReserveQuantity(v int32) {
	o.TotalVisibleReserveQuantity = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *QuoteDetailsResponseProductsInnerPrice) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuoteDetailsResponseProductsInnerPrice) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *QuoteDetailsResponseProductsInnerPrice) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *QuoteDetailsResponseProductsInnerPrice) SetType(v string) {
	o.Type = &v
}

// GetRecurringPriceModel returns the RecurringPriceModel field value if set, zero value otherwise.
func (o *QuoteDetailsResponseProductsInnerPrice) GetRecurringPriceModel() string {
	if o == nil || IsNil(o.RecurringPriceModel) {
		var ret string
		return ret
	}
	return *o.RecurringPriceModel
}

// GetRecurringPriceModelOk returns a tuple with the RecurringPriceModel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuoteDetailsResponseProductsInnerPrice) GetRecurringPriceModelOk() (*string, bool) {
	if o == nil || IsNil(o.RecurringPriceModel) {
		return nil, false
	}
	return o.RecurringPriceModel, true
}

// HasRecurringPriceModel returns a boolean if a field has been set.
func (o *QuoteDetailsResponseProductsInnerPrice) HasRecurringPriceModel() bool {
	if o != nil && !IsNil(o.RecurringPriceModel) {
		return true
	}

	return false
}

// SetRecurringPriceModel gets a reference to the given string and assigns it to the RecurringPriceModel field.
func (o *QuoteDetailsResponseProductsInnerPrice) SetRecurringPriceModel(v string) {
	o.RecurringPriceModel = &v
}

func (o QuoteDetailsResponseProductsInnerPrice) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o QuoteDetailsResponseProductsInnerPrice) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.QuotePrice) {
		toSerialize["quotePrice"] = o.QuotePrice
	}
	if !IsNil(o.Msrp) {
		toSerialize["msrp"] = o.Msrp
	}
	if !IsNil(o.ExtendedMsrp) {
		toSerialize["extendedMsrp"] = o.ExtendedMsrp
	}
	if !IsNil(o.ExtendedQuotePrice) {
		toSerialize["extendedQuotePrice"] = o.ExtendedQuotePrice
	}
	if !IsNil(o.DiscountOffList) {
		toSerialize["discountOffList"] = o.DiscountOffList
	}
	if !IsNil(o.Vendorprice) {
		toSerialize["vendorprice"] = o.Vendorprice
	}
	if !IsNil(o.Extendedvendorprice) {
		toSerialize["extendedvendorprice"] = o.Extendedvendorprice
	}
	if !IsNil(o.TotalVisibleReserveQuantity) {
		toSerialize["totalVisibleReserveQuantity"] = o.TotalVisibleReserveQuantity
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.RecurringPriceModel) {
		toSerialize["recurringPriceModel"] = o.RecurringPriceModel
	}
	return toSerialize, nil
}

type NullableQuoteDetailsResponseProductsInnerPrice struct {
	value *QuoteDetailsResponseProductsInnerPrice
	isSet bool
}

func (v NullableQuoteDetailsResponseProductsInnerPrice) Get() *QuoteDetailsResponseProductsInnerPrice {
	return v.value
}

func (v *NullableQuoteDetailsResponseProductsInnerPrice) Set(val *QuoteDetailsResponseProductsInnerPrice) {
	v.value = val
	v.isSet = true
}

func (v NullableQuoteDetailsResponseProductsInnerPrice) IsSet() bool {
	return v.isSet
}

func (v *NullableQuoteDetailsResponseProductsInnerPrice) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableQuoteDetailsResponseProductsInnerPrice(val *QuoteDetailsResponseProductsInnerPrice) *NullableQuoteDetailsResponseProductsInnerPrice {
	return &NullableQuoteDetailsResponseProductsInnerPrice{value: val, isSet: true}
}

func (v NullableQuoteDetailsResponseProductsInnerPrice) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableQuoteDetailsResponseProductsInnerPrice) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


