/*
Reseller API Documentation

For Resellers. <br> Who are looking to Innovate with Ingram Micro's API SolutionsAutomate your eCommerce with our offering of APIs and Webhooks to create a seamless experience for your customers.

API version: 6.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package xi-sdk-resellers-go

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the OrderSearchResponseServiceResponseOrdersearchresponseOrdersInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OrderSearchResponseServiceResponseOrdersearchresponseOrdersInner{}

// OrderSearchResponseServiceResponseOrdersearchresponseOrdersInner struct for OrderSearchResponseServiceResponseOrdersearchresponseOrdersInner
type OrderSearchResponseServiceResponseOrdersearchresponseOrdersInner struct {
	// Ingram micro sales order number
	Ordernumber string `json:"ordernumber"`
	// The order creation date-time in UTC format
	Entrytimestamp string `json:"entrytimestamp"`
	// PO/Order number submitted while creating the order
	Customerordernumber *string `json:"customerordernumber,omitempty"`
	// An order MAY get divided into various sub orders, for example if the SKUs are being shipped from different warehouse.
	Suborders []OrderSearchResponseServiceResponseOrdersearchresponseOrdersInnerSubordersInner `json:"suborders,omitempty"`
	Links *OrderSearchResponseServiceResponseOrdersearchresponseOrdersInnerLinks `json:"links,omitempty"`
}

type _OrderSearchResponseServiceResponseOrdersearchresponseOrdersInner OrderSearchResponseServiceResponseOrdersearchresponseOrdersInner

// NewOrderSearchResponseServiceResponseOrdersearchresponseOrdersInner instantiates a new OrderSearchResponseServiceResponseOrdersearchresponseOrdersInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOrderSearchResponseServiceResponseOrdersearchresponseOrdersInner(ordernumber string, entrytimestamp string) *OrderSearchResponseServiceResponseOrdersearchresponseOrdersInner {
	this := OrderSearchResponseServiceResponseOrdersearchresponseOrdersInner{}
	this.Ordernumber = ordernumber
	this.Entrytimestamp = entrytimestamp
	return &this
}

// NewOrderSearchResponseServiceResponseOrdersearchresponseOrdersInnerWithDefaults instantiates a new OrderSearchResponseServiceResponseOrdersearchresponseOrdersInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOrderSearchResponseServiceResponseOrdersearchresponseOrdersInnerWithDefaults() *OrderSearchResponseServiceResponseOrdersearchresponseOrdersInner {
	this := OrderSearchResponseServiceResponseOrdersearchresponseOrdersInner{}
	return &this
}

// GetOrdernumber returns the Ordernumber field value
func (o *OrderSearchResponseServiceResponseOrdersearchresponseOrdersInner) GetOrdernumber() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Ordernumber
}

// GetOrdernumberOk returns a tuple with the Ordernumber field value
// and a boolean to check if the value has been set.
func (o *OrderSearchResponseServiceResponseOrdersearchresponseOrdersInner) GetOrdernumberOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Ordernumber, true
}

// SetOrdernumber sets field value
func (o *OrderSearchResponseServiceResponseOrdersearchresponseOrdersInner) SetOrdernumber(v string) {
	o.Ordernumber = v
}

// GetEntrytimestamp returns the Entrytimestamp field value
func (o *OrderSearchResponseServiceResponseOrdersearchresponseOrdersInner) GetEntrytimestamp() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Entrytimestamp
}

// GetEntrytimestampOk returns a tuple with the Entrytimestamp field value
// and a boolean to check if the value has been set.
func (o *OrderSearchResponseServiceResponseOrdersearchresponseOrdersInner) GetEntrytimestampOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Entrytimestamp, true
}

// SetEntrytimestamp sets field value
func (o *OrderSearchResponseServiceResponseOrdersearchresponseOrdersInner) SetEntrytimestamp(v string) {
	o.Entrytimestamp = v
}

// GetCustomerordernumber returns the Customerordernumber field value if set, zero value otherwise.
func (o *OrderSearchResponseServiceResponseOrdersearchresponseOrdersInner) GetCustomerordernumber() string {
	if o == nil || IsNil(o.Customerordernumber) {
		var ret string
		return ret
	}
	return *o.Customerordernumber
}

// GetCustomerordernumberOk returns a tuple with the Customerordernumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderSearchResponseServiceResponseOrdersearchresponseOrdersInner) GetCustomerordernumberOk() (*string, bool) {
	if o == nil || IsNil(o.Customerordernumber) {
		return nil, false
	}
	return o.Customerordernumber, true
}

// HasCustomerordernumber returns a boolean if a field has been set.
func (o *OrderSearchResponseServiceResponseOrdersearchresponseOrdersInner) HasCustomerordernumber() bool {
	if o != nil && !IsNil(o.Customerordernumber) {
		return true
	}

	return false
}

// SetCustomerordernumber gets a reference to the given string and assigns it to the Customerordernumber field.
func (o *OrderSearchResponseServiceResponseOrdersearchresponseOrdersInner) SetCustomerordernumber(v string) {
	o.Customerordernumber = &v
}

// GetSuborders returns the Suborders field value if set, zero value otherwise.
func (o *OrderSearchResponseServiceResponseOrdersearchresponseOrdersInner) GetSuborders() []OrderSearchResponseServiceResponseOrdersearchresponseOrdersInnerSubordersInner {
	if o == nil || IsNil(o.Suborders) {
		var ret []OrderSearchResponseServiceResponseOrdersearchresponseOrdersInnerSubordersInner
		return ret
	}
	return o.Suborders
}

// GetSubordersOk returns a tuple with the Suborders field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderSearchResponseServiceResponseOrdersearchresponseOrdersInner) GetSubordersOk() ([]OrderSearchResponseServiceResponseOrdersearchresponseOrdersInnerSubordersInner, bool) {
	if o == nil || IsNil(o.Suborders) {
		return nil, false
	}
	return o.Suborders, true
}

// HasSuborders returns a boolean if a field has been set.
func (o *OrderSearchResponseServiceResponseOrdersearchresponseOrdersInner) HasSuborders() bool {
	if o != nil && !IsNil(o.Suborders) {
		return true
	}

	return false
}

// SetSuborders gets a reference to the given []OrderSearchResponseServiceResponseOrdersearchresponseOrdersInnerSubordersInner and assigns it to the Suborders field.
func (o *OrderSearchResponseServiceResponseOrdersearchresponseOrdersInner) SetSuborders(v []OrderSearchResponseServiceResponseOrdersearchresponseOrdersInnerSubordersInner) {
	o.Suborders = v
}

// GetLinks returns the Links field value if set, zero value otherwise.
func (o *OrderSearchResponseServiceResponseOrdersearchresponseOrdersInner) GetLinks() OrderSearchResponseServiceResponseOrdersearchresponseOrdersInnerLinks {
	if o == nil || IsNil(o.Links) {
		var ret OrderSearchResponseServiceResponseOrdersearchresponseOrdersInnerLinks
		return ret
	}
	return *o.Links
}

// GetLinksOk returns a tuple with the Links field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderSearchResponseServiceResponseOrdersearchresponseOrdersInner) GetLinksOk() (*OrderSearchResponseServiceResponseOrdersearchresponseOrdersInnerLinks, bool) {
	if o == nil || IsNil(o.Links) {
		return nil, false
	}
	return o.Links, true
}

// HasLinks returns a boolean if a field has been set.
func (o *OrderSearchResponseServiceResponseOrdersearchresponseOrdersInner) HasLinks() bool {
	if o != nil && !IsNil(o.Links) {
		return true
	}

	return false
}

// SetLinks gets a reference to the given OrderSearchResponseServiceResponseOrdersearchresponseOrdersInnerLinks and assigns it to the Links field.
func (o *OrderSearchResponseServiceResponseOrdersearchresponseOrdersInner) SetLinks(v OrderSearchResponseServiceResponseOrdersearchresponseOrdersInnerLinks) {
	o.Links = &v
}

func (o OrderSearchResponseServiceResponseOrdersearchresponseOrdersInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OrderSearchResponseServiceResponseOrdersearchresponseOrdersInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["ordernumber"] = o.Ordernumber
	toSerialize["entrytimestamp"] = o.Entrytimestamp
	if !IsNil(o.Customerordernumber) {
		toSerialize["customerordernumber"] = o.Customerordernumber
	}
	if !IsNil(o.Suborders) {
		toSerialize["suborders"] = o.Suborders
	}
	if !IsNil(o.Links) {
		toSerialize["links"] = o.Links
	}
	return toSerialize, nil
}

func (o *OrderSearchResponseServiceResponseOrdersearchresponseOrdersInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"ordernumber",
		"entrytimestamp",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOrderSearchResponseServiceResponseOrdersearchresponseOrdersInner := _OrderSearchResponseServiceResponseOrdersearchresponseOrdersInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varOrderSearchResponseServiceResponseOrdersearchresponseOrdersInner)

	if err != nil {
		return err
	}

	*o = OrderSearchResponseServiceResponseOrdersearchresponseOrdersInner(varOrderSearchResponseServiceResponseOrdersearchresponseOrdersInner)

	return err
}

type NullableOrderSearchResponseServiceResponseOrdersearchresponseOrdersInner struct {
	value *OrderSearchResponseServiceResponseOrdersearchresponseOrdersInner
	isSet bool
}

func (v NullableOrderSearchResponseServiceResponseOrdersearchresponseOrdersInner) Get() *OrderSearchResponseServiceResponseOrdersearchresponseOrdersInner {
	return v.value
}

func (v *NullableOrderSearchResponseServiceResponseOrdersearchresponseOrdersInner) Set(val *OrderSearchResponseServiceResponseOrdersearchresponseOrdersInner) {
	v.value = val
	v.isSet = true
}

func (v NullableOrderSearchResponseServiceResponseOrdersearchresponseOrdersInner) IsSet() bool {
	return v.isSet
}

func (v *NullableOrderSearchResponseServiceResponseOrdersearchresponseOrdersInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrderSearchResponseServiceResponseOrdersearchresponseOrdersInner(val *OrderSearchResponseServiceResponseOrdersearchresponseOrdersInner) *NullableOrderSearchResponseServiceResponseOrdersearchresponseOrdersInner {
	return &NullableOrderSearchResponseServiceResponseOrdersearchresponseOrdersInner{value: val, isSet: true}
}

func (v NullableOrderSearchResponseServiceResponseOrdersearchresponseOrdersInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrderSearchResponseServiceResponseOrdersearchresponseOrdersInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


