/*
Reseller API Documentation

For Resellers. <br> Who are looking to Innovate with Ingram Micro's API SolutionsAutomate your eCommerce with our offering of APIs and Webhooks to create a seamless experience for your customers.

API version: 6.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package xi-sdk-resellers-go

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the OrderCreateRequestOrdercreaterequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OrderCreateRequestOrdercreaterequest{}

// OrderCreateRequestOrdercreaterequest struct for OrderCreateRequestOrdercreaterequest
type OrderCreateRequestOrdercreaterequest struct {
	Requestpreamble OrderCreateRequestOrdercreaterequestRequestpreamble `json:"requestpreamble"`
	Ordercreatedetails *OrderCreateRequestOrdercreaterequestOrdercreatedetails `json:"ordercreatedetails,omitempty"`
}

type _OrderCreateRequestOrdercreaterequest OrderCreateRequestOrdercreaterequest

// NewOrderCreateRequestOrdercreaterequest instantiates a new OrderCreateRequestOrdercreaterequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOrderCreateRequestOrdercreaterequest(requestpreamble OrderCreateRequestOrdercreaterequestRequestpreamble) *OrderCreateRequestOrdercreaterequest {
	this := OrderCreateRequestOrdercreaterequest{}
	this.Requestpreamble = requestpreamble
	return &this
}

// NewOrderCreateRequestOrdercreaterequestWithDefaults instantiates a new OrderCreateRequestOrdercreaterequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOrderCreateRequestOrdercreaterequestWithDefaults() *OrderCreateRequestOrdercreaterequest {
	this := OrderCreateRequestOrdercreaterequest{}
	return &this
}

// GetRequestpreamble returns the Requestpreamble field value
func (o *OrderCreateRequestOrdercreaterequest) GetRequestpreamble() OrderCreateRequestOrdercreaterequestRequestpreamble {
	if o == nil {
		var ret OrderCreateRequestOrdercreaterequestRequestpreamble
		return ret
	}

	return o.Requestpreamble
}

// GetRequestpreambleOk returns a tuple with the Requestpreamble field value
// and a boolean to check if the value has been set.
func (o *OrderCreateRequestOrdercreaterequest) GetRequestpreambleOk() (*OrderCreateRequestOrdercreaterequestRequestpreamble, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Requestpreamble, true
}

// SetRequestpreamble sets field value
func (o *OrderCreateRequestOrdercreaterequest) SetRequestpreamble(v OrderCreateRequestOrdercreaterequestRequestpreamble) {
	o.Requestpreamble = v
}

// GetOrdercreatedetails returns the Ordercreatedetails field value if set, zero value otherwise.
func (o *OrderCreateRequestOrdercreaterequest) GetOrdercreatedetails() OrderCreateRequestOrdercreaterequestOrdercreatedetails {
	if o == nil || IsNil(o.Ordercreatedetails) {
		var ret OrderCreateRequestOrdercreaterequestOrdercreatedetails
		return ret
	}
	return *o.Ordercreatedetails
}

// GetOrdercreatedetailsOk returns a tuple with the Ordercreatedetails field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderCreateRequestOrdercreaterequest) GetOrdercreatedetailsOk() (*OrderCreateRequestOrdercreaterequestOrdercreatedetails, bool) {
	if o == nil || IsNil(o.Ordercreatedetails) {
		return nil, false
	}
	return o.Ordercreatedetails, true
}

// HasOrdercreatedetails returns a boolean if a field has been set.
func (o *OrderCreateRequestOrdercreaterequest) HasOrdercreatedetails() bool {
	if o != nil && !IsNil(o.Ordercreatedetails) {
		return true
	}

	return false
}

// SetOrdercreatedetails gets a reference to the given OrderCreateRequestOrdercreaterequestOrdercreatedetails and assigns it to the Ordercreatedetails field.
func (o *OrderCreateRequestOrdercreaterequest) SetOrdercreatedetails(v OrderCreateRequestOrdercreaterequestOrdercreatedetails) {
	o.Ordercreatedetails = &v
}

func (o OrderCreateRequestOrdercreaterequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OrderCreateRequestOrdercreaterequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["requestpreamble"] = o.Requestpreamble
	if !IsNil(o.Ordercreatedetails) {
		toSerialize["ordercreatedetails"] = o.Ordercreatedetails
	}
	return toSerialize, nil
}

func (o *OrderCreateRequestOrdercreaterequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"requestpreamble",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOrderCreateRequestOrdercreaterequest := _OrderCreateRequestOrdercreaterequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varOrderCreateRequestOrdercreaterequest)

	if err != nil {
		return err
	}

	*o = OrderCreateRequestOrdercreaterequest(varOrderCreateRequestOrdercreaterequest)

	return err
}

type NullableOrderCreateRequestOrdercreaterequest struct {
	value *OrderCreateRequestOrdercreaterequest
	isSet bool
}

func (v NullableOrderCreateRequestOrdercreaterequest) Get() *OrderCreateRequestOrdercreaterequest {
	return v.value
}

func (v *NullableOrderCreateRequestOrdercreaterequest) Set(val *OrderCreateRequestOrdercreaterequest) {
	v.value = val
	v.isSet = true
}

func (v NullableOrderCreateRequestOrdercreaterequest) IsSet() bool {
	return v.isSet
}

func (v *NullableOrderCreateRequestOrdercreaterequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrderCreateRequestOrdercreaterequest(val *OrderCreateRequestOrdercreaterequest) *NullableOrderCreateRequestOrdercreaterequest {
	return &NullableOrderCreateRequestOrdercreaterequest{value: val, isSet: true}
}

func (v NullableOrderCreateRequestOrdercreaterequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrderCreateRequestOrdercreaterequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


