/*
Reseller API Documentation

For Resellers. <br> Who are looking to Innovate with Ingram Micro's API SolutionsAutomate your eCommerce with our offering of APIs and Webhooks to create a seamless experience for your customers.

API version: 6.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package xi-sdk-resellers-go

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PriceAndAvailabilityRequestServicerequestRequestpreamble type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PriceAndAvailabilityRequestServicerequestRequestpreamble{}

// PriceAndAvailabilityRequestServicerequestRequestpreamble struct for PriceAndAvailabilityRequestServicerequestRequestpreamble
type PriceAndAvailabilityRequestServicerequestRequestpreamble struct {
	// 2 Digit ISO country code
	Isocountrycode string `json:"isocountrycode"`
	// Your Ingram Micro customer number
	Customernumber string `json:"customernumber"`
}

type _PriceAndAvailabilityRequestServicerequestRequestpreamble PriceAndAvailabilityRequestServicerequestRequestpreamble

// NewPriceAndAvailabilityRequestServicerequestRequestpreamble instantiates a new PriceAndAvailabilityRequestServicerequestRequestpreamble object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPriceAndAvailabilityRequestServicerequestRequestpreamble(isocountrycode string, customernumber string) *PriceAndAvailabilityRequestServicerequestRequestpreamble {
	this := PriceAndAvailabilityRequestServicerequestRequestpreamble{}
	this.Isocountrycode = isocountrycode
	this.Customernumber = customernumber
	return &this
}

// NewPriceAndAvailabilityRequestServicerequestRequestpreambleWithDefaults instantiates a new PriceAndAvailabilityRequestServicerequestRequestpreamble object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPriceAndAvailabilityRequestServicerequestRequestpreambleWithDefaults() *PriceAndAvailabilityRequestServicerequestRequestpreamble {
	this := PriceAndAvailabilityRequestServicerequestRequestpreamble{}
	return &this
}

// GetIsocountrycode returns the Isocountrycode field value
func (o *PriceAndAvailabilityRequestServicerequestRequestpreamble) GetIsocountrycode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Isocountrycode
}

// GetIsocountrycodeOk returns a tuple with the Isocountrycode field value
// and a boolean to check if the value has been set.
func (o *PriceAndAvailabilityRequestServicerequestRequestpreamble) GetIsocountrycodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Isocountrycode, true
}

// SetIsocountrycode sets field value
func (o *PriceAndAvailabilityRequestServicerequestRequestpreamble) SetIsocountrycode(v string) {
	o.Isocountrycode = v
}

// GetCustomernumber returns the Customernumber field value
func (o *PriceAndAvailabilityRequestServicerequestRequestpreamble) GetCustomernumber() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Customernumber
}

// GetCustomernumberOk returns a tuple with the Customernumber field value
// and a boolean to check if the value has been set.
func (o *PriceAndAvailabilityRequestServicerequestRequestpreamble) GetCustomernumberOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Customernumber, true
}

// SetCustomernumber sets field value
func (o *PriceAndAvailabilityRequestServicerequestRequestpreamble) SetCustomernumber(v string) {
	o.Customernumber = v
}

func (o PriceAndAvailabilityRequestServicerequestRequestpreamble) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PriceAndAvailabilityRequestServicerequestRequestpreamble) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["isocountrycode"] = o.Isocountrycode
	toSerialize["customernumber"] = o.Customernumber
	return toSerialize, nil
}

func (o *PriceAndAvailabilityRequestServicerequestRequestpreamble) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"isocountrycode",
		"customernumber",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPriceAndAvailabilityRequestServicerequestRequestpreamble := _PriceAndAvailabilityRequestServicerequestRequestpreamble{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPriceAndAvailabilityRequestServicerequestRequestpreamble)

	if err != nil {
		return err
	}

	*o = PriceAndAvailabilityRequestServicerequestRequestpreamble(varPriceAndAvailabilityRequestServicerequestRequestpreamble)

	return err
}

type NullablePriceAndAvailabilityRequestServicerequestRequestpreamble struct {
	value *PriceAndAvailabilityRequestServicerequestRequestpreamble
	isSet bool
}

func (v NullablePriceAndAvailabilityRequestServicerequestRequestpreamble) Get() *PriceAndAvailabilityRequestServicerequestRequestpreamble {
	return v.value
}

func (v *NullablePriceAndAvailabilityRequestServicerequestRequestpreamble) Set(val *PriceAndAvailabilityRequestServicerequestRequestpreamble) {
	v.value = val
	v.isSet = true
}

func (v NullablePriceAndAvailabilityRequestServicerequestRequestpreamble) IsSet() bool {
	return v.isSet
}

func (v *NullablePriceAndAvailabilityRequestServicerequestRequestpreamble) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePriceAndAvailabilityRequestServicerequestRequestpreamble(val *PriceAndAvailabilityRequestServicerequestRequestpreamble) *NullablePriceAndAvailabilityRequestServicerequestRequestpreamble {
	return &NullablePriceAndAvailabilityRequestServicerequestRequestpreamble{value: val, isSet: true}
}

func (v NullablePriceAndAvailabilityRequestServicerequestRequestpreamble) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePriceAndAvailabilityRequestServicerequestRequestpreamble) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


