/*
Reseller API Documentation

For Resellers. <br> Who are looking to Innovate with Ingram Micro's API SolutionsAutomate your eCommerce with our offering of APIs and Webhooks to create a seamless experience for your customers.

API version: 6.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package xi-sdk-resellers-go

import (
	"encoding/json"
)

// checks if the QuoteDetailsQuoteDetailResponseRetrieveQuoteResponseContactInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &QuoteDetailsQuoteDetailResponseRetrieveQuoteResponseContactInfo{}

// QuoteDetailsQuoteDetailResponseRetrieveQuoteResponseContactInfo struct for QuoteDetailsQuoteDetailResponseRetrieveQuoteResponseContactInfo
type QuoteDetailsQuoteDetailResponseRetrieveQuoteResponseContactInfo struct {
	ContactEmail *string `json:"contactEmail,omitempty"`
	ContactName *string `json:"contactName,omitempty"`
}

// NewQuoteDetailsQuoteDetailResponseRetrieveQuoteResponseContactInfo instantiates a new QuoteDetailsQuoteDetailResponseRetrieveQuoteResponseContactInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewQuoteDetailsQuoteDetailResponseRetrieveQuoteResponseContactInfo() *QuoteDetailsQuoteDetailResponseRetrieveQuoteResponseContactInfo {
	this := QuoteDetailsQuoteDetailResponseRetrieveQuoteResponseContactInfo{}
	return &this
}

// NewQuoteDetailsQuoteDetailResponseRetrieveQuoteResponseContactInfoWithDefaults instantiates a new QuoteDetailsQuoteDetailResponseRetrieveQuoteResponseContactInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewQuoteDetailsQuoteDetailResponseRetrieveQuoteResponseContactInfoWithDefaults() *QuoteDetailsQuoteDetailResponseRetrieveQuoteResponseContactInfo {
	this := QuoteDetailsQuoteDetailResponseRetrieveQuoteResponseContactInfo{}
	return &this
}

// GetContactEmail returns the ContactEmail field value if set, zero value otherwise.
func (o *QuoteDetailsQuoteDetailResponseRetrieveQuoteResponseContactInfo) GetContactEmail() string {
	if o == nil || IsNil(o.ContactEmail) {
		var ret string
		return ret
	}
	return *o.ContactEmail
}

// GetContactEmailOk returns a tuple with the ContactEmail field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuoteDetailsQuoteDetailResponseRetrieveQuoteResponseContactInfo) GetContactEmailOk() (*string, bool) {
	if o == nil || IsNil(o.ContactEmail) {
		return nil, false
	}
	return o.ContactEmail, true
}

// HasContactEmail returns a boolean if a field has been set.
func (o *QuoteDetailsQuoteDetailResponseRetrieveQuoteResponseContactInfo) HasContactEmail() bool {
	if o != nil && !IsNil(o.ContactEmail) {
		return true
	}

	return false
}

// SetContactEmail gets a reference to the given string and assigns it to the ContactEmail field.
func (o *QuoteDetailsQuoteDetailResponseRetrieveQuoteResponseContactInfo) SetContactEmail(v string) {
	o.ContactEmail = &v
}

// GetContactName returns the ContactName field value if set, zero value otherwise.
func (o *QuoteDetailsQuoteDetailResponseRetrieveQuoteResponseContactInfo) GetContactName() string {
	if o == nil || IsNil(o.ContactName) {
		var ret string
		return ret
	}
	return *o.ContactName
}

// GetContactNameOk returns a tuple with the ContactName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuoteDetailsQuoteDetailResponseRetrieveQuoteResponseContactInfo) GetContactNameOk() (*string, bool) {
	if o == nil || IsNil(o.ContactName) {
		return nil, false
	}
	return o.ContactName, true
}

// HasContactName returns a boolean if a field has been set.
func (o *QuoteDetailsQuoteDetailResponseRetrieveQuoteResponseContactInfo) HasContactName() bool {
	if o != nil && !IsNil(o.ContactName) {
		return true
	}

	return false
}

// SetContactName gets a reference to the given string and assigns it to the ContactName field.
func (o *QuoteDetailsQuoteDetailResponseRetrieveQuoteResponseContactInfo) SetContactName(v string) {
	o.ContactName = &v
}

func (o QuoteDetailsQuoteDetailResponseRetrieveQuoteResponseContactInfo) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o QuoteDetailsQuoteDetailResponseRetrieveQuoteResponseContactInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ContactEmail) {
		toSerialize["contactEmail"] = o.ContactEmail
	}
	if !IsNil(o.ContactName) {
		toSerialize["contactName"] = o.ContactName
	}
	return toSerialize, nil
}

type NullableQuoteDetailsQuoteDetailResponseRetrieveQuoteResponseContactInfo struct {
	value *QuoteDetailsQuoteDetailResponseRetrieveQuoteResponseContactInfo
	isSet bool
}

func (v NullableQuoteDetailsQuoteDetailResponseRetrieveQuoteResponseContactInfo) Get() *QuoteDetailsQuoteDetailResponseRetrieveQuoteResponseContactInfo {
	return v.value
}

func (v *NullableQuoteDetailsQuoteDetailResponseRetrieveQuoteResponseContactInfo) Set(val *QuoteDetailsQuoteDetailResponseRetrieveQuoteResponseContactInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableQuoteDetailsQuoteDetailResponseRetrieveQuoteResponseContactInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableQuoteDetailsQuoteDetailResponseRetrieveQuoteResponseContactInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableQuoteDetailsQuoteDetailResponseRetrieveQuoteResponseContactInfo(val *QuoteDetailsQuoteDetailResponseRetrieveQuoteResponseContactInfo) *NullableQuoteDetailsQuoteDetailResponseRetrieveQuoteResponseContactInfo {
	return &NullableQuoteDetailsQuoteDetailResponseRetrieveQuoteResponseContactInfo{value: val, isSet: true}
}

func (v NullableQuoteDetailsQuoteDetailResponseRetrieveQuoteResponseContactInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableQuoteDetailsQuoteDetailResponseRetrieveQuoteResponseContactInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


