/*
XI Sdk Resellers

For Resellers. Who are looking to Innovate with Ingram Micro's API SolutionsAutomate your eCommerce with our offering of APIs and Webhooks to create a seamless experience for your customers.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package xi_sdk_resellers

import (
	"encoding/json"
)

// checks if the QuoteDetailsQuoteDetailResponseRetrieveQuoteResponseAccountInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &QuoteDetailsQuoteDetailResponseRetrieveQuoteResponseAccountInfo{}

// QuoteDetailsQuoteDetailResponseRetrieveQuoteResponseAccountInfo struct for QuoteDetailsQuoteDetailResponseRetrieveQuoteResponseAccountInfo
type QuoteDetailsQuoteDetailResponseRetrieveQuoteResponseAccountInfo struct {
	AccountName *string `json:"accountName,omitempty"`
	Bcn *string `json:"bcn,omitempty"`
	Phone *string `json:"phone,omitempty"`
}

// NewQuoteDetailsQuoteDetailResponseRetrieveQuoteResponseAccountInfo instantiates a new QuoteDetailsQuoteDetailResponseRetrieveQuoteResponseAccountInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewQuoteDetailsQuoteDetailResponseRetrieveQuoteResponseAccountInfo() *QuoteDetailsQuoteDetailResponseRetrieveQuoteResponseAccountInfo {
	this := QuoteDetailsQuoteDetailResponseRetrieveQuoteResponseAccountInfo{}
	return &this
}

// NewQuoteDetailsQuoteDetailResponseRetrieveQuoteResponseAccountInfoWithDefaults instantiates a new QuoteDetailsQuoteDetailResponseRetrieveQuoteResponseAccountInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewQuoteDetailsQuoteDetailResponseRetrieveQuoteResponseAccountInfoWithDefaults() *QuoteDetailsQuoteDetailResponseRetrieveQuoteResponseAccountInfo {
	this := QuoteDetailsQuoteDetailResponseRetrieveQuoteResponseAccountInfo{}
	return &this
}

// GetAccountName returns the AccountName field value if set, zero value otherwise.
func (o *QuoteDetailsQuoteDetailResponseRetrieveQuoteResponseAccountInfo) GetAccountName() string {
	if o == nil || IsNil(o.AccountName) {
		var ret string
		return ret
	}
	return *o.AccountName
}

// GetAccountNameOk returns a tuple with the AccountName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuoteDetailsQuoteDetailResponseRetrieveQuoteResponseAccountInfo) GetAccountNameOk() (*string, bool) {
	if o == nil || IsNil(o.AccountName) {
		return nil, false
	}
	return o.AccountName, true
}

// HasAccountName returns a boolean if a field has been set.
func (o *QuoteDetailsQuoteDetailResponseRetrieveQuoteResponseAccountInfo) HasAccountName() bool {
	if o != nil && !IsNil(o.AccountName) {
		return true
	}

	return false
}

// SetAccountName gets a reference to the given string and assigns it to the AccountName field.
func (o *QuoteDetailsQuoteDetailResponseRetrieveQuoteResponseAccountInfo) SetAccountName(v string) {
	o.AccountName = &v
}

// GetBcn returns the Bcn field value if set, zero value otherwise.
func (o *QuoteDetailsQuoteDetailResponseRetrieveQuoteResponseAccountInfo) GetBcn() string {
	if o == nil || IsNil(o.Bcn) {
		var ret string
		return ret
	}
	return *o.Bcn
}

// GetBcnOk returns a tuple with the Bcn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuoteDetailsQuoteDetailResponseRetrieveQuoteResponseAccountInfo) GetBcnOk() (*string, bool) {
	if o == nil || IsNil(o.Bcn) {
		return nil, false
	}
	return o.Bcn, true
}

// HasBcn returns a boolean if a field has been set.
func (o *QuoteDetailsQuoteDetailResponseRetrieveQuoteResponseAccountInfo) HasBcn() bool {
	if o != nil && !IsNil(o.Bcn) {
		return true
	}

	return false
}

// SetBcn gets a reference to the given string and assigns it to the Bcn field.
func (o *QuoteDetailsQuoteDetailResponseRetrieveQuoteResponseAccountInfo) SetBcn(v string) {
	o.Bcn = &v
}

// GetPhone returns the Phone field value if set, zero value otherwise.
func (o *QuoteDetailsQuoteDetailResponseRetrieveQuoteResponseAccountInfo) GetPhone() string {
	if o == nil || IsNil(o.Phone) {
		var ret string
		return ret
	}
	return *o.Phone
}

// GetPhoneOk returns a tuple with the Phone field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuoteDetailsQuoteDetailResponseRetrieveQuoteResponseAccountInfo) GetPhoneOk() (*string, bool) {
	if o == nil || IsNil(o.Phone) {
		return nil, false
	}
	return o.Phone, true
}

// HasPhone returns a boolean if a field has been set.
func (o *QuoteDetailsQuoteDetailResponseRetrieveQuoteResponseAccountInfo) HasPhone() bool {
	if o != nil && !IsNil(o.Phone) {
		return true
	}

	return false
}

// SetPhone gets a reference to the given string and assigns it to the Phone field.
func (o *QuoteDetailsQuoteDetailResponseRetrieveQuoteResponseAccountInfo) SetPhone(v string) {
	o.Phone = &v
}

func (o QuoteDetailsQuoteDetailResponseRetrieveQuoteResponseAccountInfo) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o QuoteDetailsQuoteDetailResponseRetrieveQuoteResponseAccountInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AccountName) {
		toSerialize["accountName"] = o.AccountName
	}
	if !IsNil(o.Bcn) {
		toSerialize["bcn"] = o.Bcn
	}
	if !IsNil(o.Phone) {
		toSerialize["phone"] = o.Phone
	}
	return toSerialize, nil
}

type NullableQuoteDetailsQuoteDetailResponseRetrieveQuoteResponseAccountInfo struct {
	value *QuoteDetailsQuoteDetailResponseRetrieveQuoteResponseAccountInfo
	isSet bool
}

func (v NullableQuoteDetailsQuoteDetailResponseRetrieveQuoteResponseAccountInfo) Get() *QuoteDetailsQuoteDetailResponseRetrieveQuoteResponseAccountInfo {
	return v.value
}

func (v *NullableQuoteDetailsQuoteDetailResponseRetrieveQuoteResponseAccountInfo) Set(val *QuoteDetailsQuoteDetailResponseRetrieveQuoteResponseAccountInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableQuoteDetailsQuoteDetailResponseRetrieveQuoteResponseAccountInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableQuoteDetailsQuoteDetailResponseRetrieveQuoteResponseAccountInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableQuoteDetailsQuoteDetailResponseRetrieveQuoteResponseAccountInfo(val *QuoteDetailsQuoteDetailResponseRetrieveQuoteResponseAccountInfo) *NullableQuoteDetailsQuoteDetailResponseRetrieveQuoteResponseAccountInfo {
	return &NullableQuoteDetailsQuoteDetailResponseRetrieveQuoteResponseAccountInfo{value: val, isSet: true}
}

func (v NullableQuoteDetailsQuoteDetailResponseRetrieveQuoteResponseAccountInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableQuoteDetailsQuoteDetailResponseRetrieveQuoteResponseAccountInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


