/*
Reseller API Documentation

For Resellers. <br> Who are looking to Innovate with Ingram Micro's API SolutionsAutomate your eCommerce with our offering of APIs and Webhooks to create a seamless experience for your customers.

API version: 6.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package xi-sdk-resellers-go

import (
	"encoding/json"
)

// checks if the OrderModifyRequestServicerequestOrdermodifyrequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OrderModifyRequestServicerequestOrdermodifyrequest{}

// OrderModifyRequestServicerequestOrdermodifyrequest struct for OrderModifyRequestServicerequestOrdermodifyrequest
type OrderModifyRequestServicerequestOrdermodifyrequest struct {
	Ingramorderbranch *string `json:"ingramorderbranch,omitempty"`
	Ingramordernumber *string `json:"ingramordernumber,omitempty"`
	Ingramorderdist *string `json:"ingramorderdist,omitempty"`
	Ingramordership *string `json:"ingramordership,omitempty"`
	Customerponumber *string `json:"customerponumber,omitempty"`
	Shipto *OrderModifyRequestServicerequestOrdermodifyrequestShipto `json:"shipto,omitempty"`
	Headerdata *OrderModifyRequestServicerequestOrdermodifyrequestHeaderdata `json:"headerdata,omitempty"`
	Linedata []OrderModifyRequestServicerequestOrdermodifyrequestLinedataInner `json:"linedata,omitempty"`
}

// NewOrderModifyRequestServicerequestOrdermodifyrequest instantiates a new OrderModifyRequestServicerequestOrdermodifyrequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOrderModifyRequestServicerequestOrdermodifyrequest() *OrderModifyRequestServicerequestOrdermodifyrequest {
	this := OrderModifyRequestServicerequestOrdermodifyrequest{}
	return &this
}

// NewOrderModifyRequestServicerequestOrdermodifyrequestWithDefaults instantiates a new OrderModifyRequestServicerequestOrdermodifyrequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOrderModifyRequestServicerequestOrdermodifyrequestWithDefaults() *OrderModifyRequestServicerequestOrdermodifyrequest {
	this := OrderModifyRequestServicerequestOrdermodifyrequest{}
	return &this
}

// GetIngramorderbranch returns the Ingramorderbranch field value if set, zero value otherwise.
func (o *OrderModifyRequestServicerequestOrdermodifyrequest) GetIngramorderbranch() string {
	if o == nil || IsNil(o.Ingramorderbranch) {
		var ret string
		return ret
	}
	return *o.Ingramorderbranch
}

// GetIngramorderbranchOk returns a tuple with the Ingramorderbranch field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderModifyRequestServicerequestOrdermodifyrequest) GetIngramorderbranchOk() (*string, bool) {
	if o == nil || IsNil(o.Ingramorderbranch) {
		return nil, false
	}
	return o.Ingramorderbranch, true
}

// HasIngramorderbranch returns a boolean if a field has been set.
func (o *OrderModifyRequestServicerequestOrdermodifyrequest) HasIngramorderbranch() bool {
	if o != nil && !IsNil(o.Ingramorderbranch) {
		return true
	}

	return false
}

// SetIngramorderbranch gets a reference to the given string and assigns it to the Ingramorderbranch field.
func (o *OrderModifyRequestServicerequestOrdermodifyrequest) SetIngramorderbranch(v string) {
	o.Ingramorderbranch = &v
}

// GetIngramordernumber returns the Ingramordernumber field value if set, zero value otherwise.
func (o *OrderModifyRequestServicerequestOrdermodifyrequest) GetIngramordernumber() string {
	if o == nil || IsNil(o.Ingramordernumber) {
		var ret string
		return ret
	}
	return *o.Ingramordernumber
}

// GetIngramordernumberOk returns a tuple with the Ingramordernumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderModifyRequestServicerequestOrdermodifyrequest) GetIngramordernumberOk() (*string, bool) {
	if o == nil || IsNil(o.Ingramordernumber) {
		return nil, false
	}
	return o.Ingramordernumber, true
}

// HasIngramordernumber returns a boolean if a field has been set.
func (o *OrderModifyRequestServicerequestOrdermodifyrequest) HasIngramordernumber() bool {
	if o != nil && !IsNil(o.Ingramordernumber) {
		return true
	}

	return false
}

// SetIngramordernumber gets a reference to the given string and assigns it to the Ingramordernumber field.
func (o *OrderModifyRequestServicerequestOrdermodifyrequest) SetIngramordernumber(v string) {
	o.Ingramordernumber = &v
}

// GetIngramorderdist returns the Ingramorderdist field value if set, zero value otherwise.
func (o *OrderModifyRequestServicerequestOrdermodifyrequest) GetIngramorderdist() string {
	if o == nil || IsNil(o.Ingramorderdist) {
		var ret string
		return ret
	}
	return *o.Ingramorderdist
}

// GetIngramorderdistOk returns a tuple with the Ingramorderdist field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderModifyRequestServicerequestOrdermodifyrequest) GetIngramorderdistOk() (*string, bool) {
	if o == nil || IsNil(o.Ingramorderdist) {
		return nil, false
	}
	return o.Ingramorderdist, true
}

// HasIngramorderdist returns a boolean if a field has been set.
func (o *OrderModifyRequestServicerequestOrdermodifyrequest) HasIngramorderdist() bool {
	if o != nil && !IsNil(o.Ingramorderdist) {
		return true
	}

	return false
}

// SetIngramorderdist gets a reference to the given string and assigns it to the Ingramorderdist field.
func (o *OrderModifyRequestServicerequestOrdermodifyrequest) SetIngramorderdist(v string) {
	o.Ingramorderdist = &v
}

// GetIngramordership returns the Ingramordership field value if set, zero value otherwise.
func (o *OrderModifyRequestServicerequestOrdermodifyrequest) GetIngramordership() string {
	if o == nil || IsNil(o.Ingramordership) {
		var ret string
		return ret
	}
	return *o.Ingramordership
}

// GetIngramordershipOk returns a tuple with the Ingramordership field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderModifyRequestServicerequestOrdermodifyrequest) GetIngramordershipOk() (*string, bool) {
	if o == nil || IsNil(o.Ingramordership) {
		return nil, false
	}
	return o.Ingramordership, true
}

// HasIngramordership returns a boolean if a field has been set.
func (o *OrderModifyRequestServicerequestOrdermodifyrequest) HasIngramordership() bool {
	if o != nil && !IsNil(o.Ingramordership) {
		return true
	}

	return false
}

// SetIngramordership gets a reference to the given string and assigns it to the Ingramordership field.
func (o *OrderModifyRequestServicerequestOrdermodifyrequest) SetIngramordership(v string) {
	o.Ingramordership = &v
}

// GetCustomerponumber returns the Customerponumber field value if set, zero value otherwise.
func (o *OrderModifyRequestServicerequestOrdermodifyrequest) GetCustomerponumber() string {
	if o == nil || IsNil(o.Customerponumber) {
		var ret string
		return ret
	}
	return *o.Customerponumber
}

// GetCustomerponumberOk returns a tuple with the Customerponumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderModifyRequestServicerequestOrdermodifyrequest) GetCustomerponumberOk() (*string, bool) {
	if o == nil || IsNil(o.Customerponumber) {
		return nil, false
	}
	return o.Customerponumber, true
}

// HasCustomerponumber returns a boolean if a field has been set.
func (o *OrderModifyRequestServicerequestOrdermodifyrequest) HasCustomerponumber() bool {
	if o != nil && !IsNil(o.Customerponumber) {
		return true
	}

	return false
}

// SetCustomerponumber gets a reference to the given string and assigns it to the Customerponumber field.
func (o *OrderModifyRequestServicerequestOrdermodifyrequest) SetCustomerponumber(v string) {
	o.Customerponumber = &v
}

// GetShipto returns the Shipto field value if set, zero value otherwise.
func (o *OrderModifyRequestServicerequestOrdermodifyrequest) GetShipto() OrderModifyRequestServicerequestOrdermodifyrequestShipto {
	if o == nil || IsNil(o.Shipto) {
		var ret OrderModifyRequestServicerequestOrdermodifyrequestShipto
		return ret
	}
	return *o.Shipto
}

// GetShiptoOk returns a tuple with the Shipto field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderModifyRequestServicerequestOrdermodifyrequest) GetShiptoOk() (*OrderModifyRequestServicerequestOrdermodifyrequestShipto, bool) {
	if o == nil || IsNil(o.Shipto) {
		return nil, false
	}
	return o.Shipto, true
}

// HasShipto returns a boolean if a field has been set.
func (o *OrderModifyRequestServicerequestOrdermodifyrequest) HasShipto() bool {
	if o != nil && !IsNil(o.Shipto) {
		return true
	}

	return false
}

// SetShipto gets a reference to the given OrderModifyRequestServicerequestOrdermodifyrequestShipto and assigns it to the Shipto field.
func (o *OrderModifyRequestServicerequestOrdermodifyrequest) SetShipto(v OrderModifyRequestServicerequestOrdermodifyrequestShipto) {
	o.Shipto = &v
}

// GetHeaderdata returns the Headerdata field value if set, zero value otherwise.
func (o *OrderModifyRequestServicerequestOrdermodifyrequest) GetHeaderdata() OrderModifyRequestServicerequestOrdermodifyrequestHeaderdata {
	if o == nil || IsNil(o.Headerdata) {
		var ret OrderModifyRequestServicerequestOrdermodifyrequestHeaderdata
		return ret
	}
	return *o.Headerdata
}

// GetHeaderdataOk returns a tuple with the Headerdata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderModifyRequestServicerequestOrdermodifyrequest) GetHeaderdataOk() (*OrderModifyRequestServicerequestOrdermodifyrequestHeaderdata, bool) {
	if o == nil || IsNil(o.Headerdata) {
		return nil, false
	}
	return o.Headerdata, true
}

// HasHeaderdata returns a boolean if a field has been set.
func (o *OrderModifyRequestServicerequestOrdermodifyrequest) HasHeaderdata() bool {
	if o != nil && !IsNil(o.Headerdata) {
		return true
	}

	return false
}

// SetHeaderdata gets a reference to the given OrderModifyRequestServicerequestOrdermodifyrequestHeaderdata and assigns it to the Headerdata field.
func (o *OrderModifyRequestServicerequestOrdermodifyrequest) SetHeaderdata(v OrderModifyRequestServicerequestOrdermodifyrequestHeaderdata) {
	o.Headerdata = &v
}

// GetLinedata returns the Linedata field value if set, zero value otherwise.
func (o *OrderModifyRequestServicerequestOrdermodifyrequest) GetLinedata() []OrderModifyRequestServicerequestOrdermodifyrequestLinedataInner {
	if o == nil || IsNil(o.Linedata) {
		var ret []OrderModifyRequestServicerequestOrdermodifyrequestLinedataInner
		return ret
	}
	return o.Linedata
}

// GetLinedataOk returns a tuple with the Linedata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderModifyRequestServicerequestOrdermodifyrequest) GetLinedataOk() ([]OrderModifyRequestServicerequestOrdermodifyrequestLinedataInner, bool) {
	if o == nil || IsNil(o.Linedata) {
		return nil, false
	}
	return o.Linedata, true
}

// HasLinedata returns a boolean if a field has been set.
func (o *OrderModifyRequestServicerequestOrdermodifyrequest) HasLinedata() bool {
	if o != nil && !IsNil(o.Linedata) {
		return true
	}

	return false
}

// SetLinedata gets a reference to the given []OrderModifyRequestServicerequestOrdermodifyrequestLinedataInner and assigns it to the Linedata field.
func (o *OrderModifyRequestServicerequestOrdermodifyrequest) SetLinedata(v []OrderModifyRequestServicerequestOrdermodifyrequestLinedataInner) {
	o.Linedata = v
}

func (o OrderModifyRequestServicerequestOrdermodifyrequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OrderModifyRequestServicerequestOrdermodifyrequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Ingramorderbranch) {
		toSerialize["ingramorderbranch"] = o.Ingramorderbranch
	}
	if !IsNil(o.Ingramordernumber) {
		toSerialize["ingramordernumber"] = o.Ingramordernumber
	}
	if !IsNil(o.Ingramorderdist) {
		toSerialize["ingramorderdist"] = o.Ingramorderdist
	}
	if !IsNil(o.Ingramordership) {
		toSerialize["ingramordership"] = o.Ingramordership
	}
	if !IsNil(o.Customerponumber) {
		toSerialize["customerponumber"] = o.Customerponumber
	}
	if !IsNil(o.Shipto) {
		toSerialize["shipto"] = o.Shipto
	}
	if !IsNil(o.Headerdata) {
		toSerialize["headerdata"] = o.Headerdata
	}
	if !IsNil(o.Linedata) {
		toSerialize["linedata"] = o.Linedata
	}
	return toSerialize, nil
}

type NullableOrderModifyRequestServicerequestOrdermodifyrequest struct {
	value *OrderModifyRequestServicerequestOrdermodifyrequest
	isSet bool
}

func (v NullableOrderModifyRequestServicerequestOrdermodifyrequest) Get() *OrderModifyRequestServicerequestOrdermodifyrequest {
	return v.value
}

func (v *NullableOrderModifyRequestServicerequestOrdermodifyrequest) Set(val *OrderModifyRequestServicerequestOrdermodifyrequest) {
	v.value = val
	v.isSet = true
}

func (v NullableOrderModifyRequestServicerequestOrdermodifyrequest) IsSet() bool {
	return v.isSet
}

func (v *NullableOrderModifyRequestServicerequestOrdermodifyrequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrderModifyRequestServicerequestOrdermodifyrequest(val *OrderModifyRequestServicerequestOrdermodifyrequest) *NullableOrderModifyRequestServicerequestOrdermodifyrequest {
	return &NullableOrderModifyRequestServicerequestOrdermodifyrequest{value: val, isSet: true}
}

func (v NullableOrderModifyRequestServicerequestOrdermodifyrequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrderModifyRequestServicerequestOrdermodifyrequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


