/*
Reseller API

For Resellers. <br> Who are looking to Innovate with Ingram Micro's API SolutionsAutomate your eCommerce with our offering of APIs and Webhooks to create a seamless experience for your customers.

API version: 6.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package xi_sdk_resellers

import (
	"encoding/json"
)

// checks if the OrderModifyRequestServicerequestOrdermodifyrequestHeaderdata type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OrderModifyRequestServicerequestOrdermodifyrequestHeaderdata{}

// OrderModifyRequestServicerequestOrdermodifyrequestHeaderdata struct for OrderModifyRequestServicerequestOrdermodifyrequestHeaderdata
type OrderModifyRequestServicerequestOrdermodifyrequestHeaderdata struct {
	Actioncode *string `json:"actioncode,omitempty"`
	Shipviacode *string `json:"shipviacode,omitempty"`
}

// NewOrderModifyRequestServicerequestOrdermodifyrequestHeaderdata instantiates a new OrderModifyRequestServicerequestOrdermodifyrequestHeaderdata object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOrderModifyRequestServicerequestOrdermodifyrequestHeaderdata() *OrderModifyRequestServicerequestOrdermodifyrequestHeaderdata {
	this := OrderModifyRequestServicerequestOrdermodifyrequestHeaderdata{}
	return &this
}

// NewOrderModifyRequestServicerequestOrdermodifyrequestHeaderdataWithDefaults instantiates a new OrderModifyRequestServicerequestOrdermodifyrequestHeaderdata object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOrderModifyRequestServicerequestOrdermodifyrequestHeaderdataWithDefaults() *OrderModifyRequestServicerequestOrdermodifyrequestHeaderdata {
	this := OrderModifyRequestServicerequestOrdermodifyrequestHeaderdata{}
	return &this
}

// GetActioncode returns the Actioncode field value if set, zero value otherwise.
func (o *OrderModifyRequestServicerequestOrdermodifyrequestHeaderdata) GetActioncode() string {
	if o == nil || IsNil(o.Actioncode) {
		var ret string
		return ret
	}
	return *o.Actioncode
}

// GetActioncodeOk returns a tuple with the Actioncode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderModifyRequestServicerequestOrdermodifyrequestHeaderdata) GetActioncodeOk() (*string, bool) {
	if o == nil || IsNil(o.Actioncode) {
		return nil, false
	}
	return o.Actioncode, true
}

// HasActioncode returns a boolean if a field has been set.
func (o *OrderModifyRequestServicerequestOrdermodifyrequestHeaderdata) HasActioncode() bool {
	if o != nil && !IsNil(o.Actioncode) {
		return true
	}

	return false
}

// SetActioncode gets a reference to the given string and assigns it to the Actioncode field.
func (o *OrderModifyRequestServicerequestOrdermodifyrequestHeaderdata) SetActioncode(v string) {
	o.Actioncode = &v
}

// GetShipviacode returns the Shipviacode field value if set, zero value otherwise.
func (o *OrderModifyRequestServicerequestOrdermodifyrequestHeaderdata) GetShipviacode() string {
	if o == nil || IsNil(o.Shipviacode) {
		var ret string
		return ret
	}
	return *o.Shipviacode
}

// GetShipviacodeOk returns a tuple with the Shipviacode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderModifyRequestServicerequestOrdermodifyrequestHeaderdata) GetShipviacodeOk() (*string, bool) {
	if o == nil || IsNil(o.Shipviacode) {
		return nil, false
	}
	return o.Shipviacode, true
}

// HasShipviacode returns a boolean if a field has been set.
func (o *OrderModifyRequestServicerequestOrdermodifyrequestHeaderdata) HasShipviacode() bool {
	if o != nil && !IsNil(o.Shipviacode) {
		return true
	}

	return false
}

// SetShipviacode gets a reference to the given string and assigns it to the Shipviacode field.
func (o *OrderModifyRequestServicerequestOrdermodifyrequestHeaderdata) SetShipviacode(v string) {
	o.Shipviacode = &v
}

func (o OrderModifyRequestServicerequestOrdermodifyrequestHeaderdata) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OrderModifyRequestServicerequestOrdermodifyrequestHeaderdata) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Actioncode) {
		toSerialize["actioncode"] = o.Actioncode
	}
	if !IsNil(o.Shipviacode) {
		toSerialize["shipviacode"] = o.Shipviacode
	}
	return toSerialize, nil
}

type NullableOrderModifyRequestServicerequestOrdermodifyrequestHeaderdata struct {
	value *OrderModifyRequestServicerequestOrdermodifyrequestHeaderdata
	isSet bool
}

func (v NullableOrderModifyRequestServicerequestOrdermodifyrequestHeaderdata) Get() *OrderModifyRequestServicerequestOrdermodifyrequestHeaderdata {
	return v.value
}

func (v *NullableOrderModifyRequestServicerequestOrdermodifyrequestHeaderdata) Set(val *OrderModifyRequestServicerequestOrdermodifyrequestHeaderdata) {
	v.value = val
	v.isSet = true
}

func (v NullableOrderModifyRequestServicerequestOrdermodifyrequestHeaderdata) IsSet() bool {
	return v.isSet
}

func (v *NullableOrderModifyRequestServicerequestOrdermodifyrequestHeaderdata) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrderModifyRequestServicerequestOrdermodifyrequestHeaderdata(val *OrderModifyRequestServicerequestOrdermodifyrequestHeaderdata) *NullableOrderModifyRequestServicerequestOrdermodifyrequestHeaderdata {
	return &NullableOrderModifyRequestServicerequestOrdermodifyrequestHeaderdata{value: val, isSet: true}
}

func (v NullableOrderModifyRequestServicerequestOrdermodifyrequestHeaderdata) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrderModifyRequestServicerequestOrdermodifyrequestHeaderdata) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


