/*
Reseller API

For Resellers. <br> Who are looking to Innovate with Ingram Micro's API SolutionsAutomate your eCommerce with our offering of APIs and Webhooks to create a seamless experience for your customers.

API version: 6.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package xi_sdk_resellers

import (
	"encoding/json"
)

// checks if the ProductSearchRequestServicerequestProductsearchrequestSearchcriteria type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProductSearchRequestServicerequestProductsearchrequestSearchcriteria{}

// ProductSearchRequestServicerequestProductsearchrequestSearchcriteria struct for ProductSearchRequestServicerequestProductsearchrequestSearchcriteria
type ProductSearchRequestServicerequestProductsearchrequestSearchcriteria struct {
	// Name of the vendor or manufacturer or brand of the product
	Vendor *string `json:"vendor,omitempty"`
	// Vendor provided part number
	Vendorpartnumber *string `json:"vendorpartnumber,omitempty"`
	// This field seraches the decriptioon of the product.
	Partdescription *string `json:"partdescription,omitempty"`
	// Universal Product Code
	UPC *string `json:"UPC,omitempty"`
	// Customer’s designated part number 
	Customerpartnumber *string `json:"customerpartnumber,omitempty"`
}

// NewProductSearchRequestServicerequestProductsearchrequestSearchcriteria instantiates a new ProductSearchRequestServicerequestProductsearchrequestSearchcriteria object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProductSearchRequestServicerequestProductsearchrequestSearchcriteria() *ProductSearchRequestServicerequestProductsearchrequestSearchcriteria {
	this := ProductSearchRequestServicerequestProductsearchrequestSearchcriteria{}
	return &this
}

// NewProductSearchRequestServicerequestProductsearchrequestSearchcriteriaWithDefaults instantiates a new ProductSearchRequestServicerequestProductsearchrequestSearchcriteria object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProductSearchRequestServicerequestProductsearchrequestSearchcriteriaWithDefaults() *ProductSearchRequestServicerequestProductsearchrequestSearchcriteria {
	this := ProductSearchRequestServicerequestProductsearchrequestSearchcriteria{}
	return &this
}

// GetVendor returns the Vendor field value if set, zero value otherwise.
func (o *ProductSearchRequestServicerequestProductsearchrequestSearchcriteria) GetVendor() string {
	if o == nil || IsNil(o.Vendor) {
		var ret string
		return ret
	}
	return *o.Vendor
}

// GetVendorOk returns a tuple with the Vendor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductSearchRequestServicerequestProductsearchrequestSearchcriteria) GetVendorOk() (*string, bool) {
	if o == nil || IsNil(o.Vendor) {
		return nil, false
	}
	return o.Vendor, true
}

// HasVendor returns a boolean if a field has been set.
func (o *ProductSearchRequestServicerequestProductsearchrequestSearchcriteria) HasVendor() bool {
	if o != nil && !IsNil(o.Vendor) {
		return true
	}

	return false
}

// SetVendor gets a reference to the given string and assigns it to the Vendor field.
func (o *ProductSearchRequestServicerequestProductsearchrequestSearchcriteria) SetVendor(v string) {
	o.Vendor = &v
}

// GetVendorpartnumber returns the Vendorpartnumber field value if set, zero value otherwise.
func (o *ProductSearchRequestServicerequestProductsearchrequestSearchcriteria) GetVendorpartnumber() string {
	if o == nil || IsNil(o.Vendorpartnumber) {
		var ret string
		return ret
	}
	return *o.Vendorpartnumber
}

// GetVendorpartnumberOk returns a tuple with the Vendorpartnumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductSearchRequestServicerequestProductsearchrequestSearchcriteria) GetVendorpartnumberOk() (*string, bool) {
	if o == nil || IsNil(o.Vendorpartnumber) {
		return nil, false
	}
	return o.Vendorpartnumber, true
}

// HasVendorpartnumber returns a boolean if a field has been set.
func (o *ProductSearchRequestServicerequestProductsearchrequestSearchcriteria) HasVendorpartnumber() bool {
	if o != nil && !IsNil(o.Vendorpartnumber) {
		return true
	}

	return false
}

// SetVendorpartnumber gets a reference to the given string and assigns it to the Vendorpartnumber field.
func (o *ProductSearchRequestServicerequestProductsearchrequestSearchcriteria) SetVendorpartnumber(v string) {
	o.Vendorpartnumber = &v
}

// GetPartdescription returns the Partdescription field value if set, zero value otherwise.
func (o *ProductSearchRequestServicerequestProductsearchrequestSearchcriteria) GetPartdescription() string {
	if o == nil || IsNil(o.Partdescription) {
		var ret string
		return ret
	}
	return *o.Partdescription
}

// GetPartdescriptionOk returns a tuple with the Partdescription field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductSearchRequestServicerequestProductsearchrequestSearchcriteria) GetPartdescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Partdescription) {
		return nil, false
	}
	return o.Partdescription, true
}

// HasPartdescription returns a boolean if a field has been set.
func (o *ProductSearchRequestServicerequestProductsearchrequestSearchcriteria) HasPartdescription() bool {
	if o != nil && !IsNil(o.Partdescription) {
		return true
	}

	return false
}

// SetPartdescription gets a reference to the given string and assigns it to the Partdescription field.
func (o *ProductSearchRequestServicerequestProductsearchrequestSearchcriteria) SetPartdescription(v string) {
	o.Partdescription = &v
}

// GetUPC returns the UPC field value if set, zero value otherwise.
func (o *ProductSearchRequestServicerequestProductsearchrequestSearchcriteria) GetUPC() string {
	if o == nil || IsNil(o.UPC) {
		var ret string
		return ret
	}
	return *o.UPC
}

// GetUPCOk returns a tuple with the UPC field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductSearchRequestServicerequestProductsearchrequestSearchcriteria) GetUPCOk() (*string, bool) {
	if o == nil || IsNil(o.UPC) {
		return nil, false
	}
	return o.UPC, true
}

// HasUPC returns a boolean if a field has been set.
func (o *ProductSearchRequestServicerequestProductsearchrequestSearchcriteria) HasUPC() bool {
	if o != nil && !IsNil(o.UPC) {
		return true
	}

	return false
}

// SetUPC gets a reference to the given string and assigns it to the UPC field.
func (o *ProductSearchRequestServicerequestProductsearchrequestSearchcriteria) SetUPC(v string) {
	o.UPC = &v
}

// GetCustomerpartnumber returns the Customerpartnumber field value if set, zero value otherwise.
func (o *ProductSearchRequestServicerequestProductsearchrequestSearchcriteria) GetCustomerpartnumber() string {
	if o == nil || IsNil(o.Customerpartnumber) {
		var ret string
		return ret
	}
	return *o.Customerpartnumber
}

// GetCustomerpartnumberOk returns a tuple with the Customerpartnumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductSearchRequestServicerequestProductsearchrequestSearchcriteria) GetCustomerpartnumberOk() (*string, bool) {
	if o == nil || IsNil(o.Customerpartnumber) {
		return nil, false
	}
	return o.Customerpartnumber, true
}

// HasCustomerpartnumber returns a boolean if a field has been set.
func (o *ProductSearchRequestServicerequestProductsearchrequestSearchcriteria) HasCustomerpartnumber() bool {
	if o != nil && !IsNil(o.Customerpartnumber) {
		return true
	}

	return false
}

// SetCustomerpartnumber gets a reference to the given string and assigns it to the Customerpartnumber field.
func (o *ProductSearchRequestServicerequestProductsearchrequestSearchcriteria) SetCustomerpartnumber(v string) {
	o.Customerpartnumber = &v
}

func (o ProductSearchRequestServicerequestProductsearchrequestSearchcriteria) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProductSearchRequestServicerequestProductsearchrequestSearchcriteria) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Vendor) {
		toSerialize["vendor"] = o.Vendor
	}
	if !IsNil(o.Vendorpartnumber) {
		toSerialize["vendorpartnumber"] = o.Vendorpartnumber
	}
	if !IsNil(o.Partdescription) {
		toSerialize["partdescription"] = o.Partdescription
	}
	if !IsNil(o.UPC) {
		toSerialize["UPC"] = o.UPC
	}
	if !IsNil(o.Customerpartnumber) {
		toSerialize["customerpartnumber"] = o.Customerpartnumber
	}
	return toSerialize, nil
}

type NullableProductSearchRequestServicerequestProductsearchrequestSearchcriteria struct {
	value *ProductSearchRequestServicerequestProductsearchrequestSearchcriteria
	isSet bool
}

func (v NullableProductSearchRequestServicerequestProductsearchrequestSearchcriteria) Get() *ProductSearchRequestServicerequestProductsearchrequestSearchcriteria {
	return v.value
}

func (v *NullableProductSearchRequestServicerequestProductsearchrequestSearchcriteria) Set(val *ProductSearchRequestServicerequestProductsearchrequestSearchcriteria) {
	v.value = val
	v.isSet = true
}

func (v NullableProductSearchRequestServicerequestProductsearchrequestSearchcriteria) IsSet() bool {
	return v.isSet
}

func (v *NullableProductSearchRequestServicerequestProductsearchrequestSearchcriteria) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProductSearchRequestServicerequestProductsearchrequestSearchcriteria(val *ProductSearchRequestServicerequestProductsearchrequestSearchcriteria) *NullableProductSearchRequestServicerequestProductsearchrequestSearchcriteria {
	return &NullableProductSearchRequestServicerequestProductsearchrequestSearchcriteria{value: val, isSet: true}
}

func (v NullableProductSearchRequestServicerequestProductsearchrequestSearchcriteria) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProductSearchRequestServicerequestProductsearchrequestSearchcriteria) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


