/*
XI Sdk Resellers

For Resellers. Who are looking to Innovate with Ingram Micro's API SolutionsAutomate your eCommerce with our offering of APIs and Webhooks to create a seamless experience for your customers.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package xi_sdk_resellers

import (
	"encoding/json"
)

// checks if the OrderDetailResponseServiceresponseOrderdetailresponseLinesInnerShipmentdetailsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OrderDetailResponseServiceresponseOrderdetailresponseLinesInnerShipmentdetailsInner{}

// OrderDetailResponseServiceresponseOrderdetailresponseLinesInnerShipmentdetailsInner struct for OrderDetailResponseServiceresponseOrderdetailresponseLinesInnerShipmentdetailsInner
type OrderDetailResponseServiceresponseOrderdetailresponseLinesInnerShipmentdetailsInner struct {
	// quantity shipped
	Quantity *float32 `json:"quantity,omitempty"`
	// date of shipment
	Shipmentdate *string `json:"shipmentdate,omitempty"`
	// Warehouse product was shipped from
	Shipfromwarehouseid *string `json:"shipfromwarehouseid,omitempty"`
	// name of the warehouse
	Warehousename *string `json:"warehousename,omitempty"`
	// Invoice Number
	Invoicenumber *string `json:"invoicenumber,omitempty"`
	// date on the invoice generated
	Invoicedate *string `json:"invoicedate,omitempty"`
	// code for current Status of the order
	Status *string `json:"status,omitempty"`
	// Description of status
	Statusdescription *string `json:"statusdescription,omitempty"`
	// date of shipment
	Shippeddate *string `json:"shippeddate,omitempty"`
	// Description of the code if the order is on hold
	Holdreasoncodedescription *string `json:"holdreasoncodedescription,omitempty"`
	// Ingram PO Number to vendors for direct ship orders
	Ponumber *string `json:"ponumber,omitempty"`
	// Helps to determine shipment type. for e.g. LTL is used for heavy shipment. SML is used for light shipment
	Carriertype *string `json:"carriertype,omitempty"`
	// 
	Carriercode *string `json:"carriercode,omitempty"`
	// Name of the carrier. If carriername is LTL then the tracking info is in the \"pronumber\" data field
	Carriername *string `json:"carriername,omitempty"`
	// 
	Pronumber *string `json:"pronumber,omitempty"`
	Packagedetails *OrderDetailResponseServiceresponseOrderdetailresponseLinesInnerShipmentdetailsInnerPackagedetails `json:"packagedetails,omitempty"`
}

// NewOrderDetailResponseServiceresponseOrderdetailresponseLinesInnerShipmentdetailsInner instantiates a new OrderDetailResponseServiceresponseOrderdetailresponseLinesInnerShipmentdetailsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOrderDetailResponseServiceresponseOrderdetailresponseLinesInnerShipmentdetailsInner() *OrderDetailResponseServiceresponseOrderdetailresponseLinesInnerShipmentdetailsInner {
	this := OrderDetailResponseServiceresponseOrderdetailresponseLinesInnerShipmentdetailsInner{}
	return &this
}

// NewOrderDetailResponseServiceresponseOrderdetailresponseLinesInnerShipmentdetailsInnerWithDefaults instantiates a new OrderDetailResponseServiceresponseOrderdetailresponseLinesInnerShipmentdetailsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOrderDetailResponseServiceresponseOrderdetailresponseLinesInnerShipmentdetailsInnerWithDefaults() *OrderDetailResponseServiceresponseOrderdetailresponseLinesInnerShipmentdetailsInner {
	this := OrderDetailResponseServiceresponseOrderdetailresponseLinesInnerShipmentdetailsInner{}
	return &this
}

// GetQuantity returns the Quantity field value if set, zero value otherwise.
func (o *OrderDetailResponseServiceresponseOrderdetailresponseLinesInnerShipmentdetailsInner) GetQuantity() float32 {
	if o == nil || IsNil(o.Quantity) {
		var ret float32
		return ret
	}
	return *o.Quantity
}

// GetQuantityOk returns a tuple with the Quantity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderDetailResponseServiceresponseOrderdetailresponseLinesInnerShipmentdetailsInner) GetQuantityOk() (*float32, bool) {
	if o == nil || IsNil(o.Quantity) {
		return nil, false
	}
	return o.Quantity, true
}

// HasQuantity returns a boolean if a field has been set.
func (o *OrderDetailResponseServiceresponseOrderdetailresponseLinesInnerShipmentdetailsInner) HasQuantity() bool {
	if o != nil && !IsNil(o.Quantity) {
		return true
	}

	return false
}

// SetQuantity gets a reference to the given float32 and assigns it to the Quantity field.
func (o *OrderDetailResponseServiceresponseOrderdetailresponseLinesInnerShipmentdetailsInner) SetQuantity(v float32) {
	o.Quantity = &v
}

// GetShipmentdate returns the Shipmentdate field value if set, zero value otherwise.
func (o *OrderDetailResponseServiceresponseOrderdetailresponseLinesInnerShipmentdetailsInner) GetShipmentdate() string {
	if o == nil || IsNil(o.Shipmentdate) {
		var ret string
		return ret
	}
	return *o.Shipmentdate
}

// GetShipmentdateOk returns a tuple with the Shipmentdate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderDetailResponseServiceresponseOrderdetailresponseLinesInnerShipmentdetailsInner) GetShipmentdateOk() (*string, bool) {
	if o == nil || IsNil(o.Shipmentdate) {
		return nil, false
	}
	return o.Shipmentdate, true
}

// HasShipmentdate returns a boolean if a field has been set.
func (o *OrderDetailResponseServiceresponseOrderdetailresponseLinesInnerShipmentdetailsInner) HasShipmentdate() bool {
	if o != nil && !IsNil(o.Shipmentdate) {
		return true
	}

	return false
}

// SetShipmentdate gets a reference to the given string and assigns it to the Shipmentdate field.
func (o *OrderDetailResponseServiceresponseOrderdetailresponseLinesInnerShipmentdetailsInner) SetShipmentdate(v string) {
	o.Shipmentdate = &v
}

// GetShipfromwarehouseid returns the Shipfromwarehouseid field value if set, zero value otherwise.
func (o *OrderDetailResponseServiceresponseOrderdetailresponseLinesInnerShipmentdetailsInner) GetShipfromwarehouseid() string {
	if o == nil || IsNil(o.Shipfromwarehouseid) {
		var ret string
		return ret
	}
	return *o.Shipfromwarehouseid
}

// GetShipfromwarehouseidOk returns a tuple with the Shipfromwarehouseid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderDetailResponseServiceresponseOrderdetailresponseLinesInnerShipmentdetailsInner) GetShipfromwarehouseidOk() (*string, bool) {
	if o == nil || IsNil(o.Shipfromwarehouseid) {
		return nil, false
	}
	return o.Shipfromwarehouseid, true
}

// HasShipfromwarehouseid returns a boolean if a field has been set.
func (o *OrderDetailResponseServiceresponseOrderdetailresponseLinesInnerShipmentdetailsInner) HasShipfromwarehouseid() bool {
	if o != nil && !IsNil(o.Shipfromwarehouseid) {
		return true
	}

	return false
}

// SetShipfromwarehouseid gets a reference to the given string and assigns it to the Shipfromwarehouseid field.
func (o *OrderDetailResponseServiceresponseOrderdetailresponseLinesInnerShipmentdetailsInner) SetShipfromwarehouseid(v string) {
	o.Shipfromwarehouseid = &v
}

// GetWarehousename returns the Warehousename field value if set, zero value otherwise.
func (o *OrderDetailResponseServiceresponseOrderdetailresponseLinesInnerShipmentdetailsInner) GetWarehousename() string {
	if o == nil || IsNil(o.Warehousename) {
		var ret string
		return ret
	}
	return *o.Warehousename
}

// GetWarehousenameOk returns a tuple with the Warehousename field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderDetailResponseServiceresponseOrderdetailresponseLinesInnerShipmentdetailsInner) GetWarehousenameOk() (*string, bool) {
	if o == nil || IsNil(o.Warehousename) {
		return nil, false
	}
	return o.Warehousename, true
}

// HasWarehousename returns a boolean if a field has been set.
func (o *OrderDetailResponseServiceresponseOrderdetailresponseLinesInnerShipmentdetailsInner) HasWarehousename() bool {
	if o != nil && !IsNil(o.Warehousename) {
		return true
	}

	return false
}

// SetWarehousename gets a reference to the given string and assigns it to the Warehousename field.
func (o *OrderDetailResponseServiceresponseOrderdetailresponseLinesInnerShipmentdetailsInner) SetWarehousename(v string) {
	o.Warehousename = &v
}

// GetInvoicenumber returns the Invoicenumber field value if set, zero value otherwise.
func (o *OrderDetailResponseServiceresponseOrderdetailresponseLinesInnerShipmentdetailsInner) GetInvoicenumber() string {
	if o == nil || IsNil(o.Invoicenumber) {
		var ret string
		return ret
	}
	return *o.Invoicenumber
}

// GetInvoicenumberOk returns a tuple with the Invoicenumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderDetailResponseServiceresponseOrderdetailresponseLinesInnerShipmentdetailsInner) GetInvoicenumberOk() (*string, bool) {
	if o == nil || IsNil(o.Invoicenumber) {
		return nil, false
	}
	return o.Invoicenumber, true
}

// HasInvoicenumber returns a boolean if a field has been set.
func (o *OrderDetailResponseServiceresponseOrderdetailresponseLinesInnerShipmentdetailsInner) HasInvoicenumber() bool {
	if o != nil && !IsNil(o.Invoicenumber) {
		return true
	}

	return false
}

// SetInvoicenumber gets a reference to the given string and assigns it to the Invoicenumber field.
func (o *OrderDetailResponseServiceresponseOrderdetailresponseLinesInnerShipmentdetailsInner) SetInvoicenumber(v string) {
	o.Invoicenumber = &v
}

// GetInvoicedate returns the Invoicedate field value if set, zero value otherwise.
func (o *OrderDetailResponseServiceresponseOrderdetailresponseLinesInnerShipmentdetailsInner) GetInvoicedate() string {
	if o == nil || IsNil(o.Invoicedate) {
		var ret string
		return ret
	}
	return *o.Invoicedate
}

// GetInvoicedateOk returns a tuple with the Invoicedate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderDetailResponseServiceresponseOrderdetailresponseLinesInnerShipmentdetailsInner) GetInvoicedateOk() (*string, bool) {
	if o == nil || IsNil(o.Invoicedate) {
		return nil, false
	}
	return o.Invoicedate, true
}

// HasInvoicedate returns a boolean if a field has been set.
func (o *OrderDetailResponseServiceresponseOrderdetailresponseLinesInnerShipmentdetailsInner) HasInvoicedate() bool {
	if o != nil && !IsNil(o.Invoicedate) {
		return true
	}

	return false
}

// SetInvoicedate gets a reference to the given string and assigns it to the Invoicedate field.
func (o *OrderDetailResponseServiceresponseOrderdetailresponseLinesInnerShipmentdetailsInner) SetInvoicedate(v string) {
	o.Invoicedate = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *OrderDetailResponseServiceresponseOrderdetailresponseLinesInnerShipmentdetailsInner) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderDetailResponseServiceresponseOrderdetailresponseLinesInnerShipmentdetailsInner) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *OrderDetailResponseServiceresponseOrderdetailresponseLinesInnerShipmentdetailsInner) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *OrderDetailResponseServiceresponseOrderdetailresponseLinesInnerShipmentdetailsInner) SetStatus(v string) {
	o.Status = &v
}

// GetStatusdescription returns the Statusdescription field value if set, zero value otherwise.
func (o *OrderDetailResponseServiceresponseOrderdetailresponseLinesInnerShipmentdetailsInner) GetStatusdescription() string {
	if o == nil || IsNil(o.Statusdescription) {
		var ret string
		return ret
	}
	return *o.Statusdescription
}

// GetStatusdescriptionOk returns a tuple with the Statusdescription field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderDetailResponseServiceresponseOrderdetailresponseLinesInnerShipmentdetailsInner) GetStatusdescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Statusdescription) {
		return nil, false
	}
	return o.Statusdescription, true
}

// HasStatusdescription returns a boolean if a field has been set.
func (o *OrderDetailResponseServiceresponseOrderdetailresponseLinesInnerShipmentdetailsInner) HasStatusdescription() bool {
	if o != nil && !IsNil(o.Statusdescription) {
		return true
	}

	return false
}

// SetStatusdescription gets a reference to the given string and assigns it to the Statusdescription field.
func (o *OrderDetailResponseServiceresponseOrderdetailresponseLinesInnerShipmentdetailsInner) SetStatusdescription(v string) {
	o.Statusdescription = &v
}

// GetShippeddate returns the Shippeddate field value if set, zero value otherwise.
func (o *OrderDetailResponseServiceresponseOrderdetailresponseLinesInnerShipmentdetailsInner) GetShippeddate() string {
	if o == nil || IsNil(o.Shippeddate) {
		var ret string
		return ret
	}
	return *o.Shippeddate
}

// GetShippeddateOk returns a tuple with the Shippeddate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderDetailResponseServiceresponseOrderdetailresponseLinesInnerShipmentdetailsInner) GetShippeddateOk() (*string, bool) {
	if o == nil || IsNil(o.Shippeddate) {
		return nil, false
	}
	return o.Shippeddate, true
}

// HasShippeddate returns a boolean if a field has been set.
func (o *OrderDetailResponseServiceresponseOrderdetailresponseLinesInnerShipmentdetailsInner) HasShippeddate() bool {
	if o != nil && !IsNil(o.Shippeddate) {
		return true
	}

	return false
}

// SetShippeddate gets a reference to the given string and assigns it to the Shippeddate field.
func (o *OrderDetailResponseServiceresponseOrderdetailresponseLinesInnerShipmentdetailsInner) SetShippeddate(v string) {
	o.Shippeddate = &v
}

// GetHoldreasoncodedescription returns the Holdreasoncodedescription field value if set, zero value otherwise.
func (o *OrderDetailResponseServiceresponseOrderdetailresponseLinesInnerShipmentdetailsInner) GetHoldreasoncodedescription() string {
	if o == nil || IsNil(o.Holdreasoncodedescription) {
		var ret string
		return ret
	}
	return *o.Holdreasoncodedescription
}

// GetHoldreasoncodedescriptionOk returns a tuple with the Holdreasoncodedescription field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderDetailResponseServiceresponseOrderdetailresponseLinesInnerShipmentdetailsInner) GetHoldreasoncodedescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Holdreasoncodedescription) {
		return nil, false
	}
	return o.Holdreasoncodedescription, true
}

// HasHoldreasoncodedescription returns a boolean if a field has been set.
func (o *OrderDetailResponseServiceresponseOrderdetailresponseLinesInnerShipmentdetailsInner) HasHoldreasoncodedescription() bool {
	if o != nil && !IsNil(o.Holdreasoncodedescription) {
		return true
	}

	return false
}

// SetHoldreasoncodedescription gets a reference to the given string and assigns it to the Holdreasoncodedescription field.
func (o *OrderDetailResponseServiceresponseOrderdetailresponseLinesInnerShipmentdetailsInner) SetHoldreasoncodedescription(v string) {
	o.Holdreasoncodedescription = &v
}

// GetPonumber returns the Ponumber field value if set, zero value otherwise.
func (o *OrderDetailResponseServiceresponseOrderdetailresponseLinesInnerShipmentdetailsInner) GetPonumber() string {
	if o == nil || IsNil(o.Ponumber) {
		var ret string
		return ret
	}
	return *o.Ponumber
}

// GetPonumberOk returns a tuple with the Ponumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderDetailResponseServiceresponseOrderdetailresponseLinesInnerShipmentdetailsInner) GetPonumberOk() (*string, bool) {
	if o == nil || IsNil(o.Ponumber) {
		return nil, false
	}
	return o.Ponumber, true
}

// HasPonumber returns a boolean if a field has been set.
func (o *OrderDetailResponseServiceresponseOrderdetailresponseLinesInnerShipmentdetailsInner) HasPonumber() bool {
	if o != nil && !IsNil(o.Ponumber) {
		return true
	}

	return false
}

// SetPonumber gets a reference to the given string and assigns it to the Ponumber field.
func (o *OrderDetailResponseServiceresponseOrderdetailresponseLinesInnerShipmentdetailsInner) SetPonumber(v string) {
	o.Ponumber = &v
}

// GetCarriertype returns the Carriertype field value if set, zero value otherwise.
func (o *OrderDetailResponseServiceresponseOrderdetailresponseLinesInnerShipmentdetailsInner) GetCarriertype() string {
	if o == nil || IsNil(o.Carriertype) {
		var ret string
		return ret
	}
	return *o.Carriertype
}

// GetCarriertypeOk returns a tuple with the Carriertype field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderDetailResponseServiceresponseOrderdetailresponseLinesInnerShipmentdetailsInner) GetCarriertypeOk() (*string, bool) {
	if o == nil || IsNil(o.Carriertype) {
		return nil, false
	}
	return o.Carriertype, true
}

// HasCarriertype returns a boolean if a field has been set.
func (o *OrderDetailResponseServiceresponseOrderdetailresponseLinesInnerShipmentdetailsInner) HasCarriertype() bool {
	if o != nil && !IsNil(o.Carriertype) {
		return true
	}

	return false
}

// SetCarriertype gets a reference to the given string and assigns it to the Carriertype field.
func (o *OrderDetailResponseServiceresponseOrderdetailresponseLinesInnerShipmentdetailsInner) SetCarriertype(v string) {
	o.Carriertype = &v
}

// GetCarriercode returns the Carriercode field value if set, zero value otherwise.
func (o *OrderDetailResponseServiceresponseOrderdetailresponseLinesInnerShipmentdetailsInner) GetCarriercode() string {
	if o == nil || IsNil(o.Carriercode) {
		var ret string
		return ret
	}
	return *o.Carriercode
}

// GetCarriercodeOk returns a tuple with the Carriercode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderDetailResponseServiceresponseOrderdetailresponseLinesInnerShipmentdetailsInner) GetCarriercodeOk() (*string, bool) {
	if o == nil || IsNil(o.Carriercode) {
		return nil, false
	}
	return o.Carriercode, true
}

// HasCarriercode returns a boolean if a field has been set.
func (o *OrderDetailResponseServiceresponseOrderdetailresponseLinesInnerShipmentdetailsInner) HasCarriercode() bool {
	if o != nil && !IsNil(o.Carriercode) {
		return true
	}

	return false
}

// SetCarriercode gets a reference to the given string and assigns it to the Carriercode field.
func (o *OrderDetailResponseServiceresponseOrderdetailresponseLinesInnerShipmentdetailsInner) SetCarriercode(v string) {
	o.Carriercode = &v
}

// GetCarriername returns the Carriername field value if set, zero value otherwise.
func (o *OrderDetailResponseServiceresponseOrderdetailresponseLinesInnerShipmentdetailsInner) GetCarriername() string {
	if o == nil || IsNil(o.Carriername) {
		var ret string
		return ret
	}
	return *o.Carriername
}

// GetCarriernameOk returns a tuple with the Carriername field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderDetailResponseServiceresponseOrderdetailresponseLinesInnerShipmentdetailsInner) GetCarriernameOk() (*string, bool) {
	if o == nil || IsNil(o.Carriername) {
		return nil, false
	}
	return o.Carriername, true
}

// HasCarriername returns a boolean if a field has been set.
func (o *OrderDetailResponseServiceresponseOrderdetailresponseLinesInnerShipmentdetailsInner) HasCarriername() bool {
	if o != nil && !IsNil(o.Carriername) {
		return true
	}

	return false
}

// SetCarriername gets a reference to the given string and assigns it to the Carriername field.
func (o *OrderDetailResponseServiceresponseOrderdetailresponseLinesInnerShipmentdetailsInner) SetCarriername(v string) {
	o.Carriername = &v
}

// GetPronumber returns the Pronumber field value if set, zero value otherwise.
func (o *OrderDetailResponseServiceresponseOrderdetailresponseLinesInnerShipmentdetailsInner) GetPronumber() string {
	if o == nil || IsNil(o.Pronumber) {
		var ret string
		return ret
	}
	return *o.Pronumber
}

// GetPronumberOk returns a tuple with the Pronumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderDetailResponseServiceresponseOrderdetailresponseLinesInnerShipmentdetailsInner) GetPronumberOk() (*string, bool) {
	if o == nil || IsNil(o.Pronumber) {
		return nil, false
	}
	return o.Pronumber, true
}

// HasPronumber returns a boolean if a field has been set.
func (o *OrderDetailResponseServiceresponseOrderdetailresponseLinesInnerShipmentdetailsInner) HasPronumber() bool {
	if o != nil && !IsNil(o.Pronumber) {
		return true
	}

	return false
}

// SetPronumber gets a reference to the given string and assigns it to the Pronumber field.
func (o *OrderDetailResponseServiceresponseOrderdetailresponseLinesInnerShipmentdetailsInner) SetPronumber(v string) {
	o.Pronumber = &v
}

// GetPackagedetails returns the Packagedetails field value if set, zero value otherwise.
func (o *OrderDetailResponseServiceresponseOrderdetailresponseLinesInnerShipmentdetailsInner) GetPackagedetails() OrderDetailResponseServiceresponseOrderdetailresponseLinesInnerShipmentdetailsInnerPackagedetails {
	if o == nil || IsNil(o.Packagedetails) {
		var ret OrderDetailResponseServiceresponseOrderdetailresponseLinesInnerShipmentdetailsInnerPackagedetails
		return ret
	}
	return *o.Packagedetails
}

// GetPackagedetailsOk returns a tuple with the Packagedetails field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderDetailResponseServiceresponseOrderdetailresponseLinesInnerShipmentdetailsInner) GetPackagedetailsOk() (*OrderDetailResponseServiceresponseOrderdetailresponseLinesInnerShipmentdetailsInnerPackagedetails, bool) {
	if o == nil || IsNil(o.Packagedetails) {
		return nil, false
	}
	return o.Packagedetails, true
}

// HasPackagedetails returns a boolean if a field has been set.
func (o *OrderDetailResponseServiceresponseOrderdetailresponseLinesInnerShipmentdetailsInner) HasPackagedetails() bool {
	if o != nil && !IsNil(o.Packagedetails) {
		return true
	}

	return false
}

// SetPackagedetails gets a reference to the given OrderDetailResponseServiceresponseOrderdetailresponseLinesInnerShipmentdetailsInnerPackagedetails and assigns it to the Packagedetails field.
func (o *OrderDetailResponseServiceresponseOrderdetailresponseLinesInnerShipmentdetailsInner) SetPackagedetails(v OrderDetailResponseServiceresponseOrderdetailresponseLinesInnerShipmentdetailsInnerPackagedetails) {
	o.Packagedetails = &v
}

func (o OrderDetailResponseServiceresponseOrderdetailresponseLinesInnerShipmentdetailsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OrderDetailResponseServiceresponseOrderdetailresponseLinesInnerShipmentdetailsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Quantity) {
		toSerialize["quantity"] = o.Quantity
	}
	if !IsNil(o.Shipmentdate) {
		toSerialize["shipmentdate"] = o.Shipmentdate
	}
	if !IsNil(o.Shipfromwarehouseid) {
		toSerialize["shipfromwarehouseid"] = o.Shipfromwarehouseid
	}
	if !IsNil(o.Warehousename) {
		toSerialize["warehousename"] = o.Warehousename
	}
	if !IsNil(o.Invoicenumber) {
		toSerialize["invoicenumber"] = o.Invoicenumber
	}
	if !IsNil(o.Invoicedate) {
		toSerialize["invoicedate"] = o.Invoicedate
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Statusdescription) {
		toSerialize["statusdescription"] = o.Statusdescription
	}
	if !IsNil(o.Shippeddate) {
		toSerialize["shippeddate"] = o.Shippeddate
	}
	if !IsNil(o.Holdreasoncodedescription) {
		toSerialize["holdreasoncodedescription"] = o.Holdreasoncodedescription
	}
	if !IsNil(o.Ponumber) {
		toSerialize["ponumber"] = o.Ponumber
	}
	if !IsNil(o.Carriertype) {
		toSerialize["carriertype"] = o.Carriertype
	}
	if !IsNil(o.Carriercode) {
		toSerialize["carriercode"] = o.Carriercode
	}
	if !IsNil(o.Carriername) {
		toSerialize["carriername"] = o.Carriername
	}
	if !IsNil(o.Pronumber) {
		toSerialize["pronumber"] = o.Pronumber
	}
	if !IsNil(o.Packagedetails) {
		toSerialize["packagedetails"] = o.Packagedetails
	}
	return toSerialize, nil
}

type NullableOrderDetailResponseServiceresponseOrderdetailresponseLinesInnerShipmentdetailsInner struct {
	value *OrderDetailResponseServiceresponseOrderdetailresponseLinesInnerShipmentdetailsInner
	isSet bool
}

func (v NullableOrderDetailResponseServiceresponseOrderdetailresponseLinesInnerShipmentdetailsInner) Get() *OrderDetailResponseServiceresponseOrderdetailresponseLinesInnerShipmentdetailsInner {
	return v.value
}

func (v *NullableOrderDetailResponseServiceresponseOrderdetailresponseLinesInnerShipmentdetailsInner) Set(val *OrderDetailResponseServiceresponseOrderdetailresponseLinesInnerShipmentdetailsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableOrderDetailResponseServiceresponseOrderdetailresponseLinesInnerShipmentdetailsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableOrderDetailResponseServiceresponseOrderdetailresponseLinesInnerShipmentdetailsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrderDetailResponseServiceresponseOrderdetailresponseLinesInnerShipmentdetailsInner(val *OrderDetailResponseServiceresponseOrderdetailresponseLinesInnerShipmentdetailsInner) *NullableOrderDetailResponseServiceresponseOrderdetailresponseLinesInnerShipmentdetailsInner {
	return &NullableOrderDetailResponseServiceresponseOrderdetailresponseLinesInnerShipmentdetailsInner{value: val, isSet: true}
}

func (v NullableOrderDetailResponseServiceresponseOrderdetailresponseLinesInnerShipmentdetailsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrderDetailResponseServiceresponseOrderdetailresponseLinesInnerShipmentdetailsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


