/*
Reseller API

For Resellers. <br> Who are looking to Innovate with Ingram Micro's API SolutionsAutomate your eCommerce with our offering of APIs and Webhooks to create a seamless experience for your customers.

API version: 6.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package xi.sdk.resellers

import (
	"encoding/json"
)

// checks if the OrderCancelResponseServiceresponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OrderCancelResponseServiceresponse{}

// OrderCancelResponseServiceresponse struct for OrderCancelResponseServiceresponse
type OrderCancelResponseServiceresponse struct {
	Responsepreamble *OrderCancelResponseServiceresponseResponsepreamble `json:"responsepreamble,omitempty"`
}

// NewOrderCancelResponseServiceresponse instantiates a new OrderCancelResponseServiceresponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOrderCancelResponseServiceresponse() *OrderCancelResponseServiceresponse {
	this := OrderCancelResponseServiceresponse{}
	return &this
}

// NewOrderCancelResponseServiceresponseWithDefaults instantiates a new OrderCancelResponseServiceresponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOrderCancelResponseServiceresponseWithDefaults() *OrderCancelResponseServiceresponse {
	this := OrderCancelResponseServiceresponse{}
	return &this
}

// GetResponsepreamble returns the Responsepreamble field value if set, zero value otherwise.
func (o *OrderCancelResponseServiceresponse) GetResponsepreamble() OrderCancelResponseServiceresponseResponsepreamble {
	if o == nil || IsNil(o.Responsepreamble) {
		var ret OrderCancelResponseServiceresponseResponsepreamble
		return ret
	}
	return *o.Responsepreamble
}

// GetResponsepreambleOk returns a tuple with the Responsepreamble field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderCancelResponseServiceresponse) GetResponsepreambleOk() (*OrderCancelResponseServiceresponseResponsepreamble, bool) {
	if o == nil || IsNil(o.Responsepreamble) {
		return nil, false
	}
	return o.Responsepreamble, true
}

// HasResponsepreamble returns a boolean if a field has been set.
func (o *OrderCancelResponseServiceresponse) HasResponsepreamble() bool {
	if o != nil && !IsNil(o.Responsepreamble) {
		return true
	}

	return false
}

// SetResponsepreamble gets a reference to the given OrderCancelResponseServiceresponseResponsepreamble and assigns it to the Responsepreamble field.
func (o *OrderCancelResponseServiceresponse) SetResponsepreamble(v OrderCancelResponseServiceresponseResponsepreamble) {
	o.Responsepreamble = &v
}

func (o OrderCancelResponseServiceresponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OrderCancelResponseServiceresponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Responsepreamble) {
		toSerialize["responsepreamble"] = o.Responsepreamble
	}
	return toSerialize, nil
}

type NullableOrderCancelResponseServiceresponse struct {
	value *OrderCancelResponseServiceresponse
	isSet bool
}

func (v NullableOrderCancelResponseServiceresponse) Get() *OrderCancelResponseServiceresponse {
	return v.value
}

func (v *NullableOrderCancelResponseServiceresponse) Set(val *OrderCancelResponseServiceresponse) {
	v.value = val
	v.isSet = true
}

func (v NullableOrderCancelResponseServiceresponse) IsSet() bool {
	return v.isSet
}

func (v *NullableOrderCancelResponseServiceresponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrderCancelResponseServiceresponse(val *OrderCancelResponseServiceresponse) *NullableOrderCancelResponseServiceresponse {
	return &NullableOrderCancelResponseServiceresponse{value: val, isSet: true}
}

func (v NullableOrderCancelResponseServiceresponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrderCancelResponseServiceresponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


