/*
XI SDK Resellers

For Resellers. Who are looking to Innovate with Ingram Micro's API SolutionsAutomate your eCommerce with our offering of APIs and Webhooks to create a seamless experience for your customers.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package xi_sdk_resellers

import (
	"encoding/json"
)

// checks if the OrderDeleteResponseServiceresponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OrderDeleteResponseServiceresponse{}

// OrderDeleteResponseServiceresponse struct for OrderDeleteResponseServiceresponse
type OrderDeleteResponseServiceresponse struct {
	Responsepreamble *OrderDeleteResponseServiceresponseResponsepreamble `json:"responsepreamble,omitempty"`
}

// NewOrderDeleteResponseServiceresponse instantiates a new OrderDeleteResponseServiceresponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOrderDeleteResponseServiceresponse() *OrderDeleteResponseServiceresponse {
	this := OrderDeleteResponseServiceresponse{}
	return &this
}

// NewOrderDeleteResponseServiceresponseWithDefaults instantiates a new OrderDeleteResponseServiceresponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOrderDeleteResponseServiceresponseWithDefaults() *OrderDeleteResponseServiceresponse {
	this := OrderDeleteResponseServiceresponse{}
	return &this
}

// GetResponsepreamble returns the Responsepreamble field value if set, zero value otherwise.
func (o *OrderDeleteResponseServiceresponse) GetResponsepreamble() OrderDeleteResponseServiceresponseResponsepreamble {
	if o == nil || IsNil(o.Responsepreamble) {
		var ret OrderDeleteResponseServiceresponseResponsepreamble
		return ret
	}
	return *o.Responsepreamble
}

// GetResponsepreambleOk returns a tuple with the Responsepreamble field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderDeleteResponseServiceresponse) GetResponsepreambleOk() (*OrderDeleteResponseServiceresponseResponsepreamble, bool) {
	if o == nil || IsNil(o.Responsepreamble) {
		return nil, false
	}
	return o.Responsepreamble, true
}

// HasResponsepreamble returns a boolean if a field has been set.
func (o *OrderDeleteResponseServiceresponse) HasResponsepreamble() bool {
	if o != nil && !IsNil(o.Responsepreamble) {
		return true
	}

	return false
}

// SetResponsepreamble gets a reference to the given OrderDeleteResponseServiceresponseResponsepreamble and assigns it to the Responsepreamble field.
func (o *OrderDeleteResponseServiceresponse) SetResponsepreamble(v OrderDeleteResponseServiceresponseResponsepreamble) {
	o.Responsepreamble = &v
}

func (o OrderDeleteResponseServiceresponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OrderDeleteResponseServiceresponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Responsepreamble) {
		toSerialize["responsepreamble"] = o.Responsepreamble
	}
	return toSerialize, nil
}

type NullableOrderDeleteResponseServiceresponse struct {
	value *OrderDeleteResponseServiceresponse
	isSet bool
}

func (v NullableOrderDeleteResponseServiceresponse) Get() *OrderDeleteResponseServiceresponse {
	return v.value
}

func (v *NullableOrderDeleteResponseServiceresponse) Set(val *OrderDeleteResponseServiceresponse) {
	v.value = val
	v.isSet = true
}

func (v NullableOrderDeleteResponseServiceresponse) IsSet() bool {
	return v.isSet
}

func (v *NullableOrderDeleteResponseServiceresponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrderDeleteResponseServiceresponse(val *OrderDeleteResponseServiceresponse) *NullableOrderDeleteResponseServiceresponse {
	return &NullableOrderDeleteResponseServiceresponse{value: val, isSet: true}
}

func (v NullableOrderDeleteResponseServiceresponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrderDeleteResponseServiceresponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


