/*
XI Sdk Resellers

For Resellers. Who are looking to Innovate with Ingram Micro's API SolutionsAutomate your eCommerce with our offering of APIs and Webhooks to create a seamless experience for your customers.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package xi_sdk_resellers

import (
	"encoding/json"
)

// checks if the ProductDetailResponseTechnicalSpecificationsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProductDetailResponseTechnicalSpecificationsInner{}

// ProductDetailResponseTechnicalSpecificationsInner struct for ProductDetailResponseTechnicalSpecificationsInner
type ProductDetailResponseTechnicalSpecificationsInner struct {
	// Example : 'Basic'
	HeaderName *string `json:"headerName,omitempty"`
	// Example : 'Product Type'
	AttributeName *string `json:"attributeName,omitempty"`
	// Example : 'Basic|Product Type|LCD Monitor'
	AttributeDisplay *string `json:"attributeDisplay,omitempty"`
	// Example : 'LCD Monitor'
	AttributeValue *string `json:"attributeValue,omitempty"`
}

// NewProductDetailResponseTechnicalSpecificationsInner instantiates a new ProductDetailResponseTechnicalSpecificationsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProductDetailResponseTechnicalSpecificationsInner() *ProductDetailResponseTechnicalSpecificationsInner {
	this := ProductDetailResponseTechnicalSpecificationsInner{}
	return &this
}

// NewProductDetailResponseTechnicalSpecificationsInnerWithDefaults instantiates a new ProductDetailResponseTechnicalSpecificationsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProductDetailResponseTechnicalSpecificationsInnerWithDefaults() *ProductDetailResponseTechnicalSpecificationsInner {
	this := ProductDetailResponseTechnicalSpecificationsInner{}
	return &this
}

// GetHeaderName returns the HeaderName field value if set, zero value otherwise.
func (o *ProductDetailResponseTechnicalSpecificationsInner) GetHeaderName() string {
	if o == nil || IsNil(o.HeaderName) {
		var ret string
		return ret
	}
	return *o.HeaderName
}

// GetHeaderNameOk returns a tuple with the HeaderName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductDetailResponseTechnicalSpecificationsInner) GetHeaderNameOk() (*string, bool) {
	if o == nil || IsNil(o.HeaderName) {
		return nil, false
	}
	return o.HeaderName, true
}

// HasHeaderName returns a boolean if a field has been set.
func (o *ProductDetailResponseTechnicalSpecificationsInner) HasHeaderName() bool {
	if o != nil && !IsNil(o.HeaderName) {
		return true
	}

	return false
}

// SetHeaderName gets a reference to the given string and assigns it to the HeaderName field.
func (o *ProductDetailResponseTechnicalSpecificationsInner) SetHeaderName(v string) {
	o.HeaderName = &v
}

// GetAttributeName returns the AttributeName field value if set, zero value otherwise.
func (o *ProductDetailResponseTechnicalSpecificationsInner) GetAttributeName() string {
	if o == nil || IsNil(o.AttributeName) {
		var ret string
		return ret
	}
	return *o.AttributeName
}

// GetAttributeNameOk returns a tuple with the AttributeName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductDetailResponseTechnicalSpecificationsInner) GetAttributeNameOk() (*string, bool) {
	if o == nil || IsNil(o.AttributeName) {
		return nil, false
	}
	return o.AttributeName, true
}

// HasAttributeName returns a boolean if a field has been set.
func (o *ProductDetailResponseTechnicalSpecificationsInner) HasAttributeName() bool {
	if o != nil && !IsNil(o.AttributeName) {
		return true
	}

	return false
}

// SetAttributeName gets a reference to the given string and assigns it to the AttributeName field.
func (o *ProductDetailResponseTechnicalSpecificationsInner) SetAttributeName(v string) {
	o.AttributeName = &v
}

// GetAttributeDisplay returns the AttributeDisplay field value if set, zero value otherwise.
func (o *ProductDetailResponseTechnicalSpecificationsInner) GetAttributeDisplay() string {
	if o == nil || IsNil(o.AttributeDisplay) {
		var ret string
		return ret
	}
	return *o.AttributeDisplay
}

// GetAttributeDisplayOk returns a tuple with the AttributeDisplay field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductDetailResponseTechnicalSpecificationsInner) GetAttributeDisplayOk() (*string, bool) {
	if o == nil || IsNil(o.AttributeDisplay) {
		return nil, false
	}
	return o.AttributeDisplay, true
}

// HasAttributeDisplay returns a boolean if a field has been set.
func (o *ProductDetailResponseTechnicalSpecificationsInner) HasAttributeDisplay() bool {
	if o != nil && !IsNil(o.AttributeDisplay) {
		return true
	}

	return false
}

// SetAttributeDisplay gets a reference to the given string and assigns it to the AttributeDisplay field.
func (o *ProductDetailResponseTechnicalSpecificationsInner) SetAttributeDisplay(v string) {
	o.AttributeDisplay = &v
}

// GetAttributeValue returns the AttributeValue field value if set, zero value otherwise.
func (o *ProductDetailResponseTechnicalSpecificationsInner) GetAttributeValue() string {
	if o == nil || IsNil(o.AttributeValue) {
		var ret string
		return ret
	}
	return *o.AttributeValue
}

// GetAttributeValueOk returns a tuple with the AttributeValue field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductDetailResponseTechnicalSpecificationsInner) GetAttributeValueOk() (*string, bool) {
	if o == nil || IsNil(o.AttributeValue) {
		return nil, false
	}
	return o.AttributeValue, true
}

// HasAttributeValue returns a boolean if a field has been set.
func (o *ProductDetailResponseTechnicalSpecificationsInner) HasAttributeValue() bool {
	if o != nil && !IsNil(o.AttributeValue) {
		return true
	}

	return false
}

// SetAttributeValue gets a reference to the given string and assigns it to the AttributeValue field.
func (o *ProductDetailResponseTechnicalSpecificationsInner) SetAttributeValue(v string) {
	o.AttributeValue = &v
}

func (o ProductDetailResponseTechnicalSpecificationsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProductDetailResponseTechnicalSpecificationsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.HeaderName) {
		toSerialize["headerName"] = o.HeaderName
	}
	if !IsNil(o.AttributeName) {
		toSerialize["attributeName"] = o.AttributeName
	}
	if !IsNil(o.AttributeDisplay) {
		toSerialize["attributeDisplay"] = o.AttributeDisplay
	}
	if !IsNil(o.AttributeValue) {
		toSerialize["attributeValue"] = o.AttributeValue
	}
	return toSerialize, nil
}

type NullableProductDetailResponseTechnicalSpecificationsInner struct {
	value *ProductDetailResponseTechnicalSpecificationsInner
	isSet bool
}

func (v NullableProductDetailResponseTechnicalSpecificationsInner) Get() *ProductDetailResponseTechnicalSpecificationsInner {
	return v.value
}

func (v *NullableProductDetailResponseTechnicalSpecificationsInner) Set(val *ProductDetailResponseTechnicalSpecificationsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableProductDetailResponseTechnicalSpecificationsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableProductDetailResponseTechnicalSpecificationsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProductDetailResponseTechnicalSpecificationsInner(val *ProductDetailResponseTechnicalSpecificationsInner) *NullableProductDetailResponseTechnicalSpecificationsInner {
	return &NullableProductDetailResponseTechnicalSpecificationsInner{value: val, isSet: true}
}

func (v NullableProductDetailResponseTechnicalSpecificationsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProductDetailResponseTechnicalSpecificationsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


