name: Find and replace in docs.
on:
    push:
      branches:
        - main
    workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - name: Find and Replace
        run: |
          find docs/ -type f -name "*.md" -exec sed -i 's/openapiclient "github.com\/GIT_USER_ID\/GIT_REPO_ID"/xi_sdk_resellers "https:\/\/github.com\/dprakash2101\/GoSDK"/g' {} +
      - name: Commit changes
        run: |
            git config --global user.email "${{ secrets.ADMIN_EMAIL }}"
            git config --global user.name "${{ secrets.ORG_NAME }}"
            git add .
            git commit -m "Replace openapiclient with Ingrammicroresellerapi"
            git push https://${{secrets.WORKFLOW_TOKEN}}@github.com/ingrammicro-xvantage/xi-sdk-resellers-go.git main